// Code generated by counterfeiter. DO NOT EDIT.
package emailfakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/notification/email"
)

type SenderFake struct {
	SendHTMLStub        func(context.Context, email.EmailMessage) error
	sendHTMLMutex       sync.RWMutex
	sendHTMLArgsForCall []struct {
		arg1 context.Context
		arg2 email.EmailMessage
	}
	sendHTMLReturns struct {
		result1 error
	}
	sendHTMLReturnsOnCall map[int]struct {
		result1 error
	}
	SendTextStub        func(context.Context, email.EmailMessage) error
	sendTextMutex       sync.RWMutex
	sendTextArgsForCall []struct {
		arg1 context.Context
		arg2 email.EmailMessage
	}
	sendTextReturns struct {
		result1 error
	}
	sendTextReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SenderFake) SendHTML(arg1 context.Context, arg2 email.EmailMessage) error {
	fake.sendHTMLMutex.Lock()
	ret, specificReturn := fake.sendHTMLReturnsOnCall[len(fake.sendHTMLArgsForCall)]
	fake.sendHTMLArgsForCall = append(fake.sendHTMLArgsForCall, struct {
		arg1 context.Context
		arg2 email.EmailMessage
	}{arg1, arg2})
	stub := fake.SendHTMLStub
	fakeReturns := fake.sendHTMLReturns
	fake.recordInvocation("SendHTML", []interface{}{arg1, arg2})
	fake.sendHTMLMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SenderFake) SendHTMLCallCount() int {
	fake.sendHTMLMutex.RLock()
	defer fake.sendHTMLMutex.RUnlock()
	return len(fake.sendHTMLArgsForCall)
}

func (fake *SenderFake) SendHTMLCalls(stub func(context.Context, email.EmailMessage) error) {
	fake.sendHTMLMutex.Lock()
	defer fake.sendHTMLMutex.Unlock()
	fake.SendHTMLStub = stub
}

func (fake *SenderFake) SendHTMLArgsForCall(i int) (context.Context, email.EmailMessage) {
	fake.sendHTMLMutex.RLock()
	defer fake.sendHTMLMutex.RUnlock()
	argsForCall := fake.sendHTMLArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SenderFake) SendHTMLReturns(result1 error) {
	fake.sendHTMLMutex.Lock()
	defer fake.sendHTMLMutex.Unlock()
	fake.SendHTMLStub = nil
	fake.sendHTMLReturns = struct {
		result1 error
	}{result1}
}

func (fake *SenderFake) SendHTMLReturnsOnCall(i int, result1 error) {
	fake.sendHTMLMutex.Lock()
	defer fake.sendHTMLMutex.Unlock()
	fake.SendHTMLStub = nil
	if fake.sendHTMLReturnsOnCall == nil {
		fake.sendHTMLReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendHTMLReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SenderFake) SendText(arg1 context.Context, arg2 email.EmailMessage) error {
	fake.sendTextMutex.Lock()
	ret, specificReturn := fake.sendTextReturnsOnCall[len(fake.sendTextArgsForCall)]
	fake.sendTextArgsForCall = append(fake.sendTextArgsForCall, struct {
		arg1 context.Context
		arg2 email.EmailMessage
	}{arg1, arg2})
	stub := fake.SendTextStub
	fakeReturns := fake.sendTextReturns
	fake.recordInvocation("SendText", []interface{}{arg1, arg2})
	fake.sendTextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SenderFake) SendTextCallCount() int {
	fake.sendTextMutex.RLock()
	defer fake.sendTextMutex.RUnlock()
	return len(fake.sendTextArgsForCall)
}

func (fake *SenderFake) SendTextCalls(stub func(context.Context, email.EmailMessage) error) {
	fake.sendTextMutex.Lock()
	defer fake.sendTextMutex.Unlock()
	fake.SendTextStub = stub
}

func (fake *SenderFake) SendTextArgsForCall(i int) (context.Context, email.EmailMessage) {
	fake.sendTextMutex.RLock()
	defer fake.sendTextMutex.RUnlock()
	argsForCall := fake.sendTextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SenderFake) SendTextReturns(result1 error) {
	fake.sendTextMutex.Lock()
	defer fake.sendTextMutex.Unlock()
	fake.SendTextStub = nil
	fake.sendTextReturns = struct {
		result1 error
	}{result1}
}

func (fake *SenderFake) SendTextReturnsOnCall(i int, result1 error) {
	fake.sendTextMutex.Lock()
	defer fake.sendTextMutex.Unlock()
	fake.SendTextStub = nil
	if fake.sendTextReturnsOnCall == nil {
		fake.sendTextReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendTextReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SenderFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SenderFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ email.EmailSender = new(SenderFake)
