// Code generated by counterfeiter. DO NOT EDIT.
package userfakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/user"
)

type ServiceFake struct {
	AddMemberStub        func(context.Context, *user.AddMemberInput) *user.AddMemberOutput
	addMemberMutex       sync.RWMutex
	addMemberArgsForCall []struct {
		arg1 context.Context
		arg2 *user.AddMemberInput
	}
	addMemberReturns struct {
		result1 *user.AddMemberOutput
	}
	addMemberReturnsOnCall map[int]struct {
		result1 *user.AddMemberOutput
	}
	DeleteMemberStub        func(context.Context, *user.DeleteMemberInput) *user.DeleteMemberOutput
	deleteMemberMutex       sync.RWMutex
	deleteMemberArgsForCall []struct {
		arg1 context.Context
		arg2 *user.DeleteMemberInput
	}
	deleteMemberReturns struct {
		result1 *user.DeleteMemberOutput
	}
	deleteMemberReturnsOnCall map[int]struct {
		result1 *user.DeleteMemberOutput
	}
	GetMemberByIdStub        func(context.Context, *user.GetMemberByIdInput) *user.GetMemberByIdOutput
	getMemberByIdMutex       sync.RWMutex
	getMemberByIdArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetMemberByIdInput
	}
	getMemberByIdReturns struct {
		result1 *user.GetMemberByIdOutput
	}
	getMemberByIdReturnsOnCall map[int]struct {
		result1 *user.GetMemberByIdOutput
	}
	GetMembersByUserIdStub        func(context.Context, *user.GetMembersByUserIdInput) *user.GetMembersByUserIdOutput
	getMembersByUserIdMutex       sync.RWMutex
	getMembersByUserIdArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetMembersByUserIdInput
	}
	getMembersByUserIdReturns struct {
		result1 *user.GetMembersByUserIdOutput
	}
	getMembersByUserIdReturnsOnCall map[int]struct {
		result1 *user.GetMembersByUserIdOutput
	}
	GetProfileByIdStub        func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput
	getProfileByIdMutex       sync.RWMutex
	getProfileByIdArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}
	getProfileByIdReturns struct {
		result1 *user.GetProfileByIdOutput
	}
	getProfileByIdReturnsOnCall map[int]struct {
		result1 *user.GetProfileByIdOutput
	}
	LoginStub        func(context.Context, *user.LoginInput) *user.LoginOutput
	loginMutex       sync.RWMutex
	loginArgsForCall []struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}
	loginReturns struct {
		result1 *user.LoginOutput
	}
	loginReturnsOnCall map[int]struct {
		result1 *user.LoginOutput
	}
	RegisterStub        func(context.Context, *user.RegisterInput) *user.RegisterOutput
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}
	registerReturns struct {
		result1 *user.RegisterOutput
	}
	registerReturnsOnCall map[int]struct {
		result1 *user.RegisterOutput
	}
	UpdateMemberInfoStub        func(context.Context, *user.UpdateMemberInfoInput) *user.UpdateMemberInfoOutput
	updateMemberInfoMutex       sync.RWMutex
	updateMemberInfoArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateMemberInfoInput
	}
	updateMemberInfoReturns struct {
		result1 *user.UpdateMemberInfoOutput
	}
	updateMemberInfoReturnsOnCall map[int]struct {
		result1 *user.UpdateMemberInfoOutput
	}
	UpdatePasswordStub        func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput
	updatePasswordMutex       sync.RWMutex
	updatePasswordArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}
	updatePasswordReturns struct {
		result1 *user.UpdatePasswordOutput
	}
	updatePasswordReturnsOnCall map[int]struct {
		result1 *user.UpdatePasswordOutput
	}
	UpdateUsernameStub        func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput
	updateUsernameMutex       sync.RWMutex
	updateUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}
	updateUsernameReturns struct {
		result1 *user.UpdateUsernameOutput
	}
	updateUsernameReturnsOnCall map[int]struct {
		result1 *user.UpdateUsernameOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) AddMember(arg1 context.Context, arg2 *user.AddMemberInput) *user.AddMemberOutput {
	fake.addMemberMutex.Lock()
	ret, specificReturn := fake.addMemberReturnsOnCall[len(fake.addMemberArgsForCall)]
	fake.addMemberArgsForCall = append(fake.addMemberArgsForCall, struct {
		arg1 context.Context
		arg2 *user.AddMemberInput
	}{arg1, arg2})
	stub := fake.AddMemberStub
	fakeReturns := fake.addMemberReturns
	fake.recordInvocation("AddMember", []interface{}{arg1, arg2})
	fake.addMemberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AddMemberCallCount() int {
	fake.addMemberMutex.RLock()
	defer fake.addMemberMutex.RUnlock()
	return len(fake.addMemberArgsForCall)
}

func (fake *ServiceFake) AddMemberCalls(stub func(context.Context, *user.AddMemberInput) *user.AddMemberOutput) {
	fake.addMemberMutex.Lock()
	defer fake.addMemberMutex.Unlock()
	fake.AddMemberStub = stub
}

func (fake *ServiceFake) AddMemberArgsForCall(i int) (context.Context, *user.AddMemberInput) {
	fake.addMemberMutex.RLock()
	defer fake.addMemberMutex.RUnlock()
	argsForCall := fake.addMemberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AddMemberReturns(result1 *user.AddMemberOutput) {
	fake.addMemberMutex.Lock()
	defer fake.addMemberMutex.Unlock()
	fake.AddMemberStub = nil
	fake.addMemberReturns = struct {
		result1 *user.AddMemberOutput
	}{result1}
}

func (fake *ServiceFake) AddMemberReturnsOnCall(i int, result1 *user.AddMemberOutput) {
	fake.addMemberMutex.Lock()
	defer fake.addMemberMutex.Unlock()
	fake.AddMemberStub = nil
	if fake.addMemberReturnsOnCall == nil {
		fake.addMemberReturnsOnCall = make(map[int]struct {
			result1 *user.AddMemberOutput
		})
	}
	fake.addMemberReturnsOnCall[i] = struct {
		result1 *user.AddMemberOutput
	}{result1}
}

func (fake *ServiceFake) DeleteMember(arg1 context.Context, arg2 *user.DeleteMemberInput) *user.DeleteMemberOutput {
	fake.deleteMemberMutex.Lock()
	ret, specificReturn := fake.deleteMemberReturnsOnCall[len(fake.deleteMemberArgsForCall)]
	fake.deleteMemberArgsForCall = append(fake.deleteMemberArgsForCall, struct {
		arg1 context.Context
		arg2 *user.DeleteMemberInput
	}{arg1, arg2})
	stub := fake.DeleteMemberStub
	fakeReturns := fake.deleteMemberReturns
	fake.recordInvocation("DeleteMember", []interface{}{arg1, arg2})
	fake.deleteMemberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) DeleteMemberCallCount() int {
	fake.deleteMemberMutex.RLock()
	defer fake.deleteMemberMutex.RUnlock()
	return len(fake.deleteMemberArgsForCall)
}

func (fake *ServiceFake) DeleteMemberCalls(stub func(context.Context, *user.DeleteMemberInput) *user.DeleteMemberOutput) {
	fake.deleteMemberMutex.Lock()
	defer fake.deleteMemberMutex.Unlock()
	fake.DeleteMemberStub = stub
}

func (fake *ServiceFake) DeleteMemberArgsForCall(i int) (context.Context, *user.DeleteMemberInput) {
	fake.deleteMemberMutex.RLock()
	defer fake.deleteMemberMutex.RUnlock()
	argsForCall := fake.deleteMemberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) DeleteMemberReturns(result1 *user.DeleteMemberOutput) {
	fake.deleteMemberMutex.Lock()
	defer fake.deleteMemberMutex.Unlock()
	fake.DeleteMemberStub = nil
	fake.deleteMemberReturns = struct {
		result1 *user.DeleteMemberOutput
	}{result1}
}

func (fake *ServiceFake) DeleteMemberReturnsOnCall(i int, result1 *user.DeleteMemberOutput) {
	fake.deleteMemberMutex.Lock()
	defer fake.deleteMemberMutex.Unlock()
	fake.DeleteMemberStub = nil
	if fake.deleteMemberReturnsOnCall == nil {
		fake.deleteMemberReturnsOnCall = make(map[int]struct {
			result1 *user.DeleteMemberOutput
		})
	}
	fake.deleteMemberReturnsOnCall[i] = struct {
		result1 *user.DeleteMemberOutput
	}{result1}
}

func (fake *ServiceFake) GetMemberById(arg1 context.Context, arg2 *user.GetMemberByIdInput) *user.GetMemberByIdOutput {
	fake.getMemberByIdMutex.Lock()
	ret, specificReturn := fake.getMemberByIdReturnsOnCall[len(fake.getMemberByIdArgsForCall)]
	fake.getMemberByIdArgsForCall = append(fake.getMemberByIdArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetMemberByIdInput
	}{arg1, arg2})
	stub := fake.GetMemberByIdStub
	fakeReturns := fake.getMemberByIdReturns
	fake.recordInvocation("GetMemberById", []interface{}{arg1, arg2})
	fake.getMemberByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetMemberByIdCallCount() int {
	fake.getMemberByIdMutex.RLock()
	defer fake.getMemberByIdMutex.RUnlock()
	return len(fake.getMemberByIdArgsForCall)
}

func (fake *ServiceFake) GetMemberByIdCalls(stub func(context.Context, *user.GetMemberByIdInput) *user.GetMemberByIdOutput) {
	fake.getMemberByIdMutex.Lock()
	defer fake.getMemberByIdMutex.Unlock()
	fake.GetMemberByIdStub = stub
}

func (fake *ServiceFake) GetMemberByIdArgsForCall(i int) (context.Context, *user.GetMemberByIdInput) {
	fake.getMemberByIdMutex.RLock()
	defer fake.getMemberByIdMutex.RUnlock()
	argsForCall := fake.getMemberByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetMemberByIdReturns(result1 *user.GetMemberByIdOutput) {
	fake.getMemberByIdMutex.Lock()
	defer fake.getMemberByIdMutex.Unlock()
	fake.GetMemberByIdStub = nil
	fake.getMemberByIdReturns = struct {
		result1 *user.GetMemberByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetMemberByIdReturnsOnCall(i int, result1 *user.GetMemberByIdOutput) {
	fake.getMemberByIdMutex.Lock()
	defer fake.getMemberByIdMutex.Unlock()
	fake.GetMemberByIdStub = nil
	if fake.getMemberByIdReturnsOnCall == nil {
		fake.getMemberByIdReturnsOnCall = make(map[int]struct {
			result1 *user.GetMemberByIdOutput
		})
	}
	fake.getMemberByIdReturnsOnCall[i] = struct {
		result1 *user.GetMemberByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetMembersByUserId(arg1 context.Context, arg2 *user.GetMembersByUserIdInput) *user.GetMembersByUserIdOutput {
	fake.getMembersByUserIdMutex.Lock()
	ret, specificReturn := fake.getMembersByUserIdReturnsOnCall[len(fake.getMembersByUserIdArgsForCall)]
	fake.getMembersByUserIdArgsForCall = append(fake.getMembersByUserIdArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetMembersByUserIdInput
	}{arg1, arg2})
	stub := fake.GetMembersByUserIdStub
	fakeReturns := fake.getMembersByUserIdReturns
	fake.recordInvocation("GetMembersByUserId", []interface{}{arg1, arg2})
	fake.getMembersByUserIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetMembersByUserIdCallCount() int {
	fake.getMembersByUserIdMutex.RLock()
	defer fake.getMembersByUserIdMutex.RUnlock()
	return len(fake.getMembersByUserIdArgsForCall)
}

func (fake *ServiceFake) GetMembersByUserIdCalls(stub func(context.Context, *user.GetMembersByUserIdInput) *user.GetMembersByUserIdOutput) {
	fake.getMembersByUserIdMutex.Lock()
	defer fake.getMembersByUserIdMutex.Unlock()
	fake.GetMembersByUserIdStub = stub
}

func (fake *ServiceFake) GetMembersByUserIdArgsForCall(i int) (context.Context, *user.GetMembersByUserIdInput) {
	fake.getMembersByUserIdMutex.RLock()
	defer fake.getMembersByUserIdMutex.RUnlock()
	argsForCall := fake.getMembersByUserIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetMembersByUserIdReturns(result1 *user.GetMembersByUserIdOutput) {
	fake.getMembersByUserIdMutex.Lock()
	defer fake.getMembersByUserIdMutex.Unlock()
	fake.GetMembersByUserIdStub = nil
	fake.getMembersByUserIdReturns = struct {
		result1 *user.GetMembersByUserIdOutput
	}{result1}
}

func (fake *ServiceFake) GetMembersByUserIdReturnsOnCall(i int, result1 *user.GetMembersByUserIdOutput) {
	fake.getMembersByUserIdMutex.Lock()
	defer fake.getMembersByUserIdMutex.Unlock()
	fake.GetMembersByUserIdStub = nil
	if fake.getMembersByUserIdReturnsOnCall == nil {
		fake.getMembersByUserIdReturnsOnCall = make(map[int]struct {
			result1 *user.GetMembersByUserIdOutput
		})
	}
	fake.getMembersByUserIdReturnsOnCall[i] = struct {
		result1 *user.GetMembersByUserIdOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileById(arg1 context.Context, arg2 *user.GetProfileByIdInput) *user.GetProfileByIdOutput {
	fake.getProfileByIdMutex.Lock()
	ret, specificReturn := fake.getProfileByIdReturnsOnCall[len(fake.getProfileByIdArgsForCall)]
	fake.getProfileByIdArgsForCall = append(fake.getProfileByIdArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}{arg1, arg2})
	stub := fake.GetProfileByIdStub
	fakeReturns := fake.getProfileByIdReturns
	fake.recordInvocation("GetProfileById", []interface{}{arg1, arg2})
	fake.getProfileByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetProfileByIdCallCount() int {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	return len(fake.getProfileByIdArgsForCall)
}

func (fake *ServiceFake) GetProfileByIdCalls(stub func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = stub
}

func (fake *ServiceFake) GetProfileByIdArgsForCall(i int) (context.Context, *user.GetProfileByIdInput) {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	argsForCall := fake.getProfileByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetProfileByIdReturns(result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	fake.getProfileByIdReturns = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileByIdReturnsOnCall(i int, result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	if fake.getProfileByIdReturnsOnCall == nil {
		fake.getProfileByIdReturnsOnCall = make(map[int]struct {
			result1 *user.GetProfileByIdOutput
		})
	}
	fake.getProfileByIdReturnsOnCall[i] = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) Login(arg1 context.Context, arg2 *user.LoginInput) *user.LoginOutput {
	fake.loginMutex.Lock()
	ret, specificReturn := fake.loginReturnsOnCall[len(fake.loginArgsForCall)]
	fake.loginArgsForCall = append(fake.loginArgsForCall, struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}{arg1, arg2})
	stub := fake.LoginStub
	fakeReturns := fake.loginReturns
	fake.recordInvocation("Login", []interface{}{arg1, arg2})
	fake.loginMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) LoginCallCount() int {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return len(fake.loginArgsForCall)
}

func (fake *ServiceFake) LoginCalls(stub func(context.Context, *user.LoginInput) *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = stub
}

func (fake *ServiceFake) LoginArgsForCall(i int) (context.Context, *user.LoginInput) {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	argsForCall := fake.loginArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) LoginReturns(result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	fake.loginReturns = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) LoginReturnsOnCall(i int, result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	if fake.loginReturnsOnCall == nil {
		fake.loginReturnsOnCall = make(map[int]struct {
			result1 *user.LoginOutput
		})
	}
	fake.loginReturnsOnCall[i] = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) Register(arg1 context.Context, arg2 *user.RegisterInput) *user.RegisterOutput {
	fake.registerMutex.Lock()
	ret, specificReturn := fake.registerReturnsOnCall[len(fake.registerArgsForCall)]
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}{arg1, arg2})
	stub := fake.RegisterStub
	fakeReturns := fake.registerReturns
	fake.recordInvocation("Register", []interface{}{arg1, arg2})
	fake.registerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *ServiceFake) RegisterCalls(stub func(context.Context, *user.RegisterInput) *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = stub
}

func (fake *ServiceFake) RegisterArgsForCall(i int) (context.Context, *user.RegisterInput) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	argsForCall := fake.registerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RegisterReturns(result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	fake.registerReturns = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) RegisterReturnsOnCall(i int, result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	if fake.registerReturnsOnCall == nil {
		fake.registerReturnsOnCall = make(map[int]struct {
			result1 *user.RegisterOutput
		})
	}
	fake.registerReturnsOnCall[i] = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) UpdateMemberInfo(arg1 context.Context, arg2 *user.UpdateMemberInfoInput) *user.UpdateMemberInfoOutput {
	fake.updateMemberInfoMutex.Lock()
	ret, specificReturn := fake.updateMemberInfoReturnsOnCall[len(fake.updateMemberInfoArgsForCall)]
	fake.updateMemberInfoArgsForCall = append(fake.updateMemberInfoArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateMemberInfoInput
	}{arg1, arg2})
	stub := fake.UpdateMemberInfoStub
	fakeReturns := fake.updateMemberInfoReturns
	fake.recordInvocation("UpdateMemberInfo", []interface{}{arg1, arg2})
	fake.updateMemberInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateMemberInfoCallCount() int {
	fake.updateMemberInfoMutex.RLock()
	defer fake.updateMemberInfoMutex.RUnlock()
	return len(fake.updateMemberInfoArgsForCall)
}

func (fake *ServiceFake) UpdateMemberInfoCalls(stub func(context.Context, *user.UpdateMemberInfoInput) *user.UpdateMemberInfoOutput) {
	fake.updateMemberInfoMutex.Lock()
	defer fake.updateMemberInfoMutex.Unlock()
	fake.UpdateMemberInfoStub = stub
}

func (fake *ServiceFake) UpdateMemberInfoArgsForCall(i int) (context.Context, *user.UpdateMemberInfoInput) {
	fake.updateMemberInfoMutex.RLock()
	defer fake.updateMemberInfoMutex.RUnlock()
	argsForCall := fake.updateMemberInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateMemberInfoReturns(result1 *user.UpdateMemberInfoOutput) {
	fake.updateMemberInfoMutex.Lock()
	defer fake.updateMemberInfoMutex.Unlock()
	fake.UpdateMemberInfoStub = nil
	fake.updateMemberInfoReturns = struct {
		result1 *user.UpdateMemberInfoOutput
	}{result1}
}

func (fake *ServiceFake) UpdateMemberInfoReturnsOnCall(i int, result1 *user.UpdateMemberInfoOutput) {
	fake.updateMemberInfoMutex.Lock()
	defer fake.updateMemberInfoMutex.Unlock()
	fake.UpdateMemberInfoStub = nil
	if fake.updateMemberInfoReturnsOnCall == nil {
		fake.updateMemberInfoReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateMemberInfoOutput
		})
	}
	fake.updateMemberInfoReturnsOnCall[i] = struct {
		result1 *user.UpdateMemberInfoOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePassword(arg1 context.Context, arg2 *user.UpdatePasswordInput) *user.UpdatePasswordOutput {
	fake.updatePasswordMutex.Lock()
	ret, specificReturn := fake.updatePasswordReturnsOnCall[len(fake.updatePasswordArgsForCall)]
	fake.updatePasswordArgsForCall = append(fake.updatePasswordArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}{arg1, arg2})
	stub := fake.UpdatePasswordStub
	fakeReturns := fake.updatePasswordReturns
	fake.recordInvocation("UpdatePassword", []interface{}{arg1, arg2})
	fake.updatePasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdatePasswordCallCount() int {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	return len(fake.updatePasswordArgsForCall)
}

func (fake *ServiceFake) UpdatePasswordCalls(stub func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = stub
}

func (fake *ServiceFake) UpdatePasswordArgsForCall(i int) (context.Context, *user.UpdatePasswordInput) {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	argsForCall := fake.updatePasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdatePasswordReturns(result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	fake.updatePasswordReturns = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePasswordReturnsOnCall(i int, result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	if fake.updatePasswordReturnsOnCall == nil {
		fake.updatePasswordReturnsOnCall = make(map[int]struct {
			result1 *user.UpdatePasswordOutput
		})
	}
	fake.updatePasswordReturnsOnCall[i] = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsername(arg1 context.Context, arg2 *user.UpdateUsernameInput) *user.UpdateUsernameOutput {
	fake.updateUsernameMutex.Lock()
	ret, specificReturn := fake.updateUsernameReturnsOnCall[len(fake.updateUsernameArgsForCall)]
	fake.updateUsernameArgsForCall = append(fake.updateUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}{arg1, arg2})
	stub := fake.UpdateUsernameStub
	fakeReturns := fake.updateUsernameReturns
	fake.recordInvocation("UpdateUsername", []interface{}{arg1, arg2})
	fake.updateUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateUsernameCallCount() int {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	return len(fake.updateUsernameArgsForCall)
}

func (fake *ServiceFake) UpdateUsernameCalls(stub func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = stub
}

func (fake *ServiceFake) UpdateUsernameArgsForCall(i int) (context.Context, *user.UpdateUsernameInput) {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	argsForCall := fake.updateUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateUsernameReturns(result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	fake.updateUsernameReturns = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsernameReturnsOnCall(i int, result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	if fake.updateUsernameReturnsOnCall == nil {
		fake.updateUsernameReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateUsernameOutput
		})
	}
	fake.updateUsernameReturnsOnCall[i] = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ user.Service = new(ServiceFake)
