// Code generated by counterfeiter. DO NOT EDIT.
package userfakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/user"
	"github.com/ariesmaulana/ars-kit/src/app/workflow"
)

type ServiceFake struct {
	DemoWorkflowStub        func(context.Context, *user.DemoWorkflowInput) *user.DemoWorkflowOutput
	demoWorkflowMutex       sync.RWMutex
	demoWorkflowArgsForCall []struct {
		arg1 context.Context
		arg2 *user.DemoWorkflowInput
	}
	demoWorkflowReturns struct {
		result1 *user.DemoWorkflowOutput
	}
	demoWorkflowReturnsOnCall map[int]struct {
		result1 *user.DemoWorkflowOutput
	}
	GetProfileByIdStub        func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput
	getProfileByIdMutex       sync.RWMutex
	getProfileByIdArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}
	getProfileByIdReturns struct {
		result1 *user.GetProfileByIdOutput
	}
	getProfileByIdReturnsOnCall map[int]struct {
		result1 *user.GetProfileByIdOutput
	}
	GrantPermissionStub        func(context.Context, *user.GrantPermissionInput) *user.GrantPermissionOutput
	grantPermissionMutex       sync.RWMutex
	grantPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GrantPermissionInput
	}
	grantPermissionReturns struct {
		result1 *user.GrantPermissionOutput
	}
	grantPermissionReturnsOnCall map[int]struct {
		result1 *user.GrantPermissionOutput
	}
	GrantPermissionSystemStub        func(context.Context, *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput
	grantPermissionSystemMutex       sync.RWMutex
	grantPermissionSystemArgsForCall []struct {
		arg1 context.Context
		arg2 *workflow.GrantPermissionInput
	}
	grantPermissionSystemReturns struct {
		result1 *workflow.GrantPermissionOutput
	}
	grantPermissionSystemReturnsOnCall map[int]struct {
		result1 *workflow.GrantPermissionOutput
	}
	LoginStub        func(context.Context, *user.LoginInput) *user.LoginOutput
	loginMutex       sync.RWMutex
	loginArgsForCall []struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}
	loginReturns struct {
		result1 *user.LoginOutput
	}
	loginReturnsOnCall map[int]struct {
		result1 *user.LoginOutput
	}
	RegisterStub        func(context.Context, *user.RegisterInput) *user.RegisterOutput
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}
	registerReturns struct {
		result1 *user.RegisterOutput
	}
	registerReturnsOnCall map[int]struct {
		result1 *user.RegisterOutput
	}
	RegisterUserStub        func(context.Context, *workflow.RegisterUserInput) *workflow.RegisterUserOutput
	registerUserMutex       sync.RWMutex
	registerUserArgsForCall []struct {
		arg1 context.Context
		arg2 *workflow.RegisterUserInput
	}
	registerUserReturns struct {
		result1 *workflow.RegisterUserOutput
	}
	registerUserReturnsOnCall map[int]struct {
		result1 *workflow.RegisterUserOutput
	}
	RevokePermissionStub        func(context.Context, *user.RevokePermissionInput) *user.RevokePermissionOutput
	revokePermissionMutex       sync.RWMutex
	revokePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RevokePermissionInput
	}
	revokePermissionReturns struct {
		result1 *user.RevokePermissionOutput
	}
	revokePermissionReturnsOnCall map[int]struct {
		result1 *user.RevokePermissionOutput
	}
	UpdateEmailStub        func(context.Context, *user.UpdateEmailInput) *user.UpdateEmailOutput
	updateEmailMutex       sync.RWMutex
	updateEmailArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateEmailInput
	}
	updateEmailReturns struct {
		result1 *user.UpdateEmailOutput
	}
	updateEmailReturnsOnCall map[int]struct {
		result1 *user.UpdateEmailOutput
	}
	UpdatePasswordStub        func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput
	updatePasswordMutex       sync.RWMutex
	updatePasswordArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}
	updatePasswordReturns struct {
		result1 *user.UpdatePasswordOutput
	}
	updatePasswordReturnsOnCall map[int]struct {
		result1 *user.UpdatePasswordOutput
	}
	UpdateProfileStub        func(context.Context, *user.UpdateProfileInput) *user.UpdateProfileOutput
	updateProfileMutex       sync.RWMutex
	updateProfileArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateProfileInput
	}
	updateProfileReturns struct {
		result1 *user.UpdateProfileOutput
	}
	updateProfileReturnsOnCall map[int]struct {
		result1 *user.UpdateProfileOutput
	}
	UpdateUsernameStub        func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput
	updateUsernameMutex       sync.RWMutex
	updateUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}
	updateUsernameReturns struct {
		result1 *user.UpdateUsernameOutput
	}
	updateUsernameReturnsOnCall map[int]struct {
		result1 *user.UpdateUsernameOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) DemoWorkflow(arg1 context.Context, arg2 *user.DemoWorkflowInput) *user.DemoWorkflowOutput {
	fake.demoWorkflowMutex.Lock()
	ret, specificReturn := fake.demoWorkflowReturnsOnCall[len(fake.demoWorkflowArgsForCall)]
	fake.demoWorkflowArgsForCall = append(fake.demoWorkflowArgsForCall, struct {
		arg1 context.Context
		arg2 *user.DemoWorkflowInput
	}{arg1, arg2})
	stub := fake.DemoWorkflowStub
	fakeReturns := fake.demoWorkflowReturns
	fake.recordInvocation("DemoWorkflow", []interface{}{arg1, arg2})
	fake.demoWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) DemoWorkflowCallCount() int {
	fake.demoWorkflowMutex.RLock()
	defer fake.demoWorkflowMutex.RUnlock()
	return len(fake.demoWorkflowArgsForCall)
}

func (fake *ServiceFake) DemoWorkflowCalls(stub func(context.Context, *user.DemoWorkflowInput) *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = stub
}

func (fake *ServiceFake) DemoWorkflowArgsForCall(i int) (context.Context, *user.DemoWorkflowInput) {
	fake.demoWorkflowMutex.RLock()
	defer fake.demoWorkflowMutex.RUnlock()
	argsForCall := fake.demoWorkflowArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) DemoWorkflowReturns(result1 *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = nil
	fake.demoWorkflowReturns = struct {
		result1 *user.DemoWorkflowOutput
	}{result1}
}

func (fake *ServiceFake) DemoWorkflowReturnsOnCall(i int, result1 *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = nil
	if fake.demoWorkflowReturnsOnCall == nil {
		fake.demoWorkflowReturnsOnCall = make(map[int]struct {
			result1 *user.DemoWorkflowOutput
		})
	}
	fake.demoWorkflowReturnsOnCall[i] = struct {
		result1 *user.DemoWorkflowOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileById(arg1 context.Context, arg2 *user.GetProfileByIdInput) *user.GetProfileByIdOutput {
	fake.getProfileByIdMutex.Lock()
	ret, specificReturn := fake.getProfileByIdReturnsOnCall[len(fake.getProfileByIdArgsForCall)]
	fake.getProfileByIdArgsForCall = append(fake.getProfileByIdArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}{arg1, arg2})
	stub := fake.GetProfileByIdStub
	fakeReturns := fake.getProfileByIdReturns
	fake.recordInvocation("GetProfileById", []interface{}{arg1, arg2})
	fake.getProfileByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetProfileByIdCallCount() int {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	return len(fake.getProfileByIdArgsForCall)
}

func (fake *ServiceFake) GetProfileByIdCalls(stub func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = stub
}

func (fake *ServiceFake) GetProfileByIdArgsForCall(i int) (context.Context, *user.GetProfileByIdInput) {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	argsForCall := fake.getProfileByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetProfileByIdReturns(result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	fake.getProfileByIdReturns = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileByIdReturnsOnCall(i int, result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	if fake.getProfileByIdReturnsOnCall == nil {
		fake.getProfileByIdReturnsOnCall = make(map[int]struct {
			result1 *user.GetProfileByIdOutput
		})
	}
	fake.getProfileByIdReturnsOnCall[i] = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermission(arg1 context.Context, arg2 *user.GrantPermissionInput) *user.GrantPermissionOutput {
	fake.grantPermissionMutex.Lock()
	ret, specificReturn := fake.grantPermissionReturnsOnCall[len(fake.grantPermissionArgsForCall)]
	fake.grantPermissionArgsForCall = append(fake.grantPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GrantPermissionInput
	}{arg1, arg2})
	stub := fake.GrantPermissionStub
	fakeReturns := fake.grantPermissionReturns
	fake.recordInvocation("GrantPermission", []interface{}{arg1, arg2})
	fake.grantPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GrantPermissionCallCount() int {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	return len(fake.grantPermissionArgsForCall)
}

func (fake *ServiceFake) GrantPermissionCalls(stub func(context.Context, *user.GrantPermissionInput) *user.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = stub
}

func (fake *ServiceFake) GrantPermissionArgsForCall(i int) (context.Context, *user.GrantPermissionInput) {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	argsForCall := fake.grantPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GrantPermissionReturns(result1 *user.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	fake.grantPermissionReturns = struct {
		result1 *user.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionReturnsOnCall(i int, result1 *user.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	if fake.grantPermissionReturnsOnCall == nil {
		fake.grantPermissionReturnsOnCall = make(map[int]struct {
			result1 *user.GrantPermissionOutput
		})
	}
	fake.grantPermissionReturnsOnCall[i] = struct {
		result1 *user.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionSystem(arg1 context.Context, arg2 *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput {
	fake.grantPermissionSystemMutex.Lock()
	ret, specificReturn := fake.grantPermissionSystemReturnsOnCall[len(fake.grantPermissionSystemArgsForCall)]
	fake.grantPermissionSystemArgsForCall = append(fake.grantPermissionSystemArgsForCall, struct {
		arg1 context.Context
		arg2 *workflow.GrantPermissionInput
	}{arg1, arg2})
	stub := fake.GrantPermissionSystemStub
	fakeReturns := fake.grantPermissionSystemReturns
	fake.recordInvocation("GrantPermissionSystem", []interface{}{arg1, arg2})
	fake.grantPermissionSystemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GrantPermissionSystemCallCount() int {
	fake.grantPermissionSystemMutex.RLock()
	defer fake.grantPermissionSystemMutex.RUnlock()
	return len(fake.grantPermissionSystemArgsForCall)
}

func (fake *ServiceFake) GrantPermissionSystemCalls(stub func(context.Context, *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = stub
}

func (fake *ServiceFake) GrantPermissionSystemArgsForCall(i int) (context.Context, *workflow.GrantPermissionInput) {
	fake.grantPermissionSystemMutex.RLock()
	defer fake.grantPermissionSystemMutex.RUnlock()
	argsForCall := fake.grantPermissionSystemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GrantPermissionSystemReturns(result1 *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = nil
	fake.grantPermissionSystemReturns = struct {
		result1 *workflow.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionSystemReturnsOnCall(i int, result1 *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = nil
	if fake.grantPermissionSystemReturnsOnCall == nil {
		fake.grantPermissionSystemReturnsOnCall = make(map[int]struct {
			result1 *workflow.GrantPermissionOutput
		})
	}
	fake.grantPermissionSystemReturnsOnCall[i] = struct {
		result1 *workflow.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) Login(arg1 context.Context, arg2 *user.LoginInput) *user.LoginOutput {
	fake.loginMutex.Lock()
	ret, specificReturn := fake.loginReturnsOnCall[len(fake.loginArgsForCall)]
	fake.loginArgsForCall = append(fake.loginArgsForCall, struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}{arg1, arg2})
	stub := fake.LoginStub
	fakeReturns := fake.loginReturns
	fake.recordInvocation("Login", []interface{}{arg1, arg2})
	fake.loginMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) LoginCallCount() int {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return len(fake.loginArgsForCall)
}

func (fake *ServiceFake) LoginCalls(stub func(context.Context, *user.LoginInput) *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = stub
}

func (fake *ServiceFake) LoginArgsForCall(i int) (context.Context, *user.LoginInput) {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	argsForCall := fake.loginArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) LoginReturns(result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	fake.loginReturns = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) LoginReturnsOnCall(i int, result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	if fake.loginReturnsOnCall == nil {
		fake.loginReturnsOnCall = make(map[int]struct {
			result1 *user.LoginOutput
		})
	}
	fake.loginReturnsOnCall[i] = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) Register(arg1 context.Context, arg2 *user.RegisterInput) *user.RegisterOutput {
	fake.registerMutex.Lock()
	ret, specificReturn := fake.registerReturnsOnCall[len(fake.registerArgsForCall)]
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}{arg1, arg2})
	stub := fake.RegisterStub
	fakeReturns := fake.registerReturns
	fake.recordInvocation("Register", []interface{}{arg1, arg2})
	fake.registerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *ServiceFake) RegisterCalls(stub func(context.Context, *user.RegisterInput) *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = stub
}

func (fake *ServiceFake) RegisterArgsForCall(i int) (context.Context, *user.RegisterInput) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	argsForCall := fake.registerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RegisterReturns(result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	fake.registerReturns = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) RegisterReturnsOnCall(i int, result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	if fake.registerReturnsOnCall == nil {
		fake.registerReturnsOnCall = make(map[int]struct {
			result1 *user.RegisterOutput
		})
	}
	fake.registerReturnsOnCall[i] = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) RegisterUser(arg1 context.Context, arg2 *workflow.RegisterUserInput) *workflow.RegisterUserOutput {
	fake.registerUserMutex.Lock()
	ret, specificReturn := fake.registerUserReturnsOnCall[len(fake.registerUserArgsForCall)]
	fake.registerUserArgsForCall = append(fake.registerUserArgsForCall, struct {
		arg1 context.Context
		arg2 *workflow.RegisterUserInput
	}{arg1, arg2})
	stub := fake.RegisterUserStub
	fakeReturns := fake.registerUserReturns
	fake.recordInvocation("RegisterUser", []interface{}{arg1, arg2})
	fake.registerUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RegisterUserCallCount() int {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	return len(fake.registerUserArgsForCall)
}

func (fake *ServiceFake) RegisterUserCalls(stub func(context.Context, *workflow.RegisterUserInput) *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = stub
}

func (fake *ServiceFake) RegisterUserArgsForCall(i int) (context.Context, *workflow.RegisterUserInput) {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	argsForCall := fake.registerUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RegisterUserReturns(result1 *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = nil
	fake.registerUserReturns = struct {
		result1 *workflow.RegisterUserOutput
	}{result1}
}

func (fake *ServiceFake) RegisterUserReturnsOnCall(i int, result1 *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = nil
	if fake.registerUserReturnsOnCall == nil {
		fake.registerUserReturnsOnCall = make(map[int]struct {
			result1 *workflow.RegisterUserOutput
		})
	}
	fake.registerUserReturnsOnCall[i] = struct {
		result1 *workflow.RegisterUserOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermission(arg1 context.Context, arg2 *user.RevokePermissionInput) *user.RevokePermissionOutput {
	fake.revokePermissionMutex.Lock()
	ret, specificReturn := fake.revokePermissionReturnsOnCall[len(fake.revokePermissionArgsForCall)]
	fake.revokePermissionArgsForCall = append(fake.revokePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RevokePermissionInput
	}{arg1, arg2})
	stub := fake.RevokePermissionStub
	fakeReturns := fake.revokePermissionReturns
	fake.recordInvocation("RevokePermission", []interface{}{arg1, arg2})
	fake.revokePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RevokePermissionCallCount() int {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	return len(fake.revokePermissionArgsForCall)
}

func (fake *ServiceFake) RevokePermissionCalls(stub func(context.Context, *user.RevokePermissionInput) *user.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = stub
}

func (fake *ServiceFake) RevokePermissionArgsForCall(i int) (context.Context, *user.RevokePermissionInput) {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	argsForCall := fake.revokePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RevokePermissionReturns(result1 *user.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	fake.revokePermissionReturns = struct {
		result1 *user.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermissionReturnsOnCall(i int, result1 *user.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	if fake.revokePermissionReturnsOnCall == nil {
		fake.revokePermissionReturnsOnCall = make(map[int]struct {
			result1 *user.RevokePermissionOutput
		})
	}
	fake.revokePermissionReturnsOnCall[i] = struct {
		result1 *user.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) UpdateEmail(arg1 context.Context, arg2 *user.UpdateEmailInput) *user.UpdateEmailOutput {
	fake.updateEmailMutex.Lock()
	ret, specificReturn := fake.updateEmailReturnsOnCall[len(fake.updateEmailArgsForCall)]
	fake.updateEmailArgsForCall = append(fake.updateEmailArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateEmailInput
	}{arg1, arg2})
	stub := fake.UpdateEmailStub
	fakeReturns := fake.updateEmailReturns
	fake.recordInvocation("UpdateEmail", []interface{}{arg1, arg2})
	fake.updateEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateEmailCallCount() int {
	fake.updateEmailMutex.RLock()
	defer fake.updateEmailMutex.RUnlock()
	return len(fake.updateEmailArgsForCall)
}

func (fake *ServiceFake) UpdateEmailCalls(stub func(context.Context, *user.UpdateEmailInput) *user.UpdateEmailOutput) {
	fake.updateEmailMutex.Lock()
	defer fake.updateEmailMutex.Unlock()
	fake.UpdateEmailStub = stub
}

func (fake *ServiceFake) UpdateEmailArgsForCall(i int) (context.Context, *user.UpdateEmailInput) {
	fake.updateEmailMutex.RLock()
	defer fake.updateEmailMutex.RUnlock()
	argsForCall := fake.updateEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateEmailReturns(result1 *user.UpdateEmailOutput) {
	fake.updateEmailMutex.Lock()
	defer fake.updateEmailMutex.Unlock()
	fake.UpdateEmailStub = nil
	fake.updateEmailReturns = struct {
		result1 *user.UpdateEmailOutput
	}{result1}
}

func (fake *ServiceFake) UpdateEmailReturnsOnCall(i int, result1 *user.UpdateEmailOutput) {
	fake.updateEmailMutex.Lock()
	defer fake.updateEmailMutex.Unlock()
	fake.UpdateEmailStub = nil
	if fake.updateEmailReturnsOnCall == nil {
		fake.updateEmailReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateEmailOutput
		})
	}
	fake.updateEmailReturnsOnCall[i] = struct {
		result1 *user.UpdateEmailOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePassword(arg1 context.Context, arg2 *user.UpdatePasswordInput) *user.UpdatePasswordOutput {
	fake.updatePasswordMutex.Lock()
	ret, specificReturn := fake.updatePasswordReturnsOnCall[len(fake.updatePasswordArgsForCall)]
	fake.updatePasswordArgsForCall = append(fake.updatePasswordArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}{arg1, arg2})
	stub := fake.UpdatePasswordStub
	fakeReturns := fake.updatePasswordReturns
	fake.recordInvocation("UpdatePassword", []interface{}{arg1, arg2})
	fake.updatePasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdatePasswordCallCount() int {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	return len(fake.updatePasswordArgsForCall)
}

func (fake *ServiceFake) UpdatePasswordCalls(stub func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = stub
}

func (fake *ServiceFake) UpdatePasswordArgsForCall(i int) (context.Context, *user.UpdatePasswordInput) {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	argsForCall := fake.updatePasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdatePasswordReturns(result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	fake.updatePasswordReturns = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePasswordReturnsOnCall(i int, result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	if fake.updatePasswordReturnsOnCall == nil {
		fake.updatePasswordReturnsOnCall = make(map[int]struct {
			result1 *user.UpdatePasswordOutput
		})
	}
	fake.updatePasswordReturnsOnCall[i] = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdateProfile(arg1 context.Context, arg2 *user.UpdateProfileInput) *user.UpdateProfileOutput {
	fake.updateProfileMutex.Lock()
	ret, specificReturn := fake.updateProfileReturnsOnCall[len(fake.updateProfileArgsForCall)]
	fake.updateProfileArgsForCall = append(fake.updateProfileArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateProfileInput
	}{arg1, arg2})
	stub := fake.UpdateProfileStub
	fakeReturns := fake.updateProfileReturns
	fake.recordInvocation("UpdateProfile", []interface{}{arg1, arg2})
	fake.updateProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateProfileCallCount() int {
	fake.updateProfileMutex.RLock()
	defer fake.updateProfileMutex.RUnlock()
	return len(fake.updateProfileArgsForCall)
}

func (fake *ServiceFake) UpdateProfileCalls(stub func(context.Context, *user.UpdateProfileInput) *user.UpdateProfileOutput) {
	fake.updateProfileMutex.Lock()
	defer fake.updateProfileMutex.Unlock()
	fake.UpdateProfileStub = stub
}

func (fake *ServiceFake) UpdateProfileArgsForCall(i int) (context.Context, *user.UpdateProfileInput) {
	fake.updateProfileMutex.RLock()
	defer fake.updateProfileMutex.RUnlock()
	argsForCall := fake.updateProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateProfileReturns(result1 *user.UpdateProfileOutput) {
	fake.updateProfileMutex.Lock()
	defer fake.updateProfileMutex.Unlock()
	fake.UpdateProfileStub = nil
	fake.updateProfileReturns = struct {
		result1 *user.UpdateProfileOutput
	}{result1}
}

func (fake *ServiceFake) UpdateProfileReturnsOnCall(i int, result1 *user.UpdateProfileOutput) {
	fake.updateProfileMutex.Lock()
	defer fake.updateProfileMutex.Unlock()
	fake.UpdateProfileStub = nil
	if fake.updateProfileReturnsOnCall == nil {
		fake.updateProfileReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateProfileOutput
		})
	}
	fake.updateProfileReturnsOnCall[i] = struct {
		result1 *user.UpdateProfileOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsername(arg1 context.Context, arg2 *user.UpdateUsernameInput) *user.UpdateUsernameOutput {
	fake.updateUsernameMutex.Lock()
	ret, specificReturn := fake.updateUsernameReturnsOnCall[len(fake.updateUsernameArgsForCall)]
	fake.updateUsernameArgsForCall = append(fake.updateUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}{arg1, arg2})
	stub := fake.UpdateUsernameStub
	fakeReturns := fake.updateUsernameReturns
	fake.recordInvocation("UpdateUsername", []interface{}{arg1, arg2})
	fake.updateUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateUsernameCallCount() int {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	return len(fake.updateUsernameArgsForCall)
}

func (fake *ServiceFake) UpdateUsernameCalls(stub func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = stub
}

func (fake *ServiceFake) UpdateUsernameArgsForCall(i int) (context.Context, *user.UpdateUsernameInput) {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	argsForCall := fake.updateUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateUsernameReturns(result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	fake.updateUsernameReturns = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsernameReturnsOnCall(i int, result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	if fake.updateUsernameReturnsOnCall == nil {
		fake.updateUsernameReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateUsernameOutput
		})
	}
	fake.updateUsernameReturnsOnCall[i] = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ user.Service = new(ServiceFake)
