// Code generated by counterfeiter. DO NOT EDIT.
package userfakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/user"
	"github.com/ariesmaulana/ars-kit/src/app/workflow"
)

type ServiceFake struct {
	AssignPermissionToRoleStub        func(context.Context, *user.AssignPermissionToRoleInput) *user.AssignPermissionToRoleOutput
	assignPermissionToRoleMutex       sync.RWMutex
	assignPermissionToRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *user.AssignPermissionToRoleInput
	}
	assignPermissionToRoleReturns struct {
		result1 *user.AssignPermissionToRoleOutput
	}
	assignPermissionToRoleReturnsOnCall map[int]struct {
		result1 *user.AssignPermissionToRoleOutput
	}
	AssignRoleStub        func(context.Context, *user.AssignRoleInput) *user.AssignRoleOutput
	assignRoleMutex       sync.RWMutex
	assignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *user.AssignRoleInput
	}
	assignRoleReturns struct {
		result1 *user.AssignRoleOutput
	}
	assignRoleReturnsOnCall map[int]struct {
		result1 *user.AssignRoleOutput
	}
	DeleteUserStub        func(context.Context, *user.DeleteUserInput) *user.DeleteUserOutput
	deleteUserMutex       sync.RWMutex
	deleteUserArgsForCall []struct {
		arg1 context.Context
		arg2 *user.DeleteUserInput
	}
	deleteUserReturns struct {
		result1 *user.DeleteUserOutput
	}
	deleteUserReturnsOnCall map[int]struct {
		result1 *user.DeleteUserOutput
	}
	DemoWorkflowStub        func(context.Context, *user.DemoWorkflowInput) *user.DemoWorkflowOutput
	demoWorkflowMutex       sync.RWMutex
	demoWorkflowArgsForCall []struct {
		arg1 context.Context
		arg2 *user.DemoWorkflowInput
	}
	demoWorkflowReturns struct {
		result1 *user.DemoWorkflowOutput
	}
	demoWorkflowReturnsOnCall map[int]struct {
		result1 *user.DemoWorkflowOutput
	}
	ForgotPasswordStub        func(context.Context, *user.ForgotPasswordInput) *user.ForgotPasswordOutput
	forgotPasswordMutex       sync.RWMutex
	forgotPasswordArgsForCall []struct {
		arg1 context.Context
		arg2 *user.ForgotPasswordInput
	}
	forgotPasswordReturns struct {
		result1 *user.ForgotPasswordOutput
	}
	forgotPasswordReturnsOnCall map[int]struct {
		result1 *user.ForgotPasswordOutput
	}
	GetProfileByIdStub        func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput
	getProfileByIdMutex       sync.RWMutex
	getProfileByIdArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}
	getProfileByIdReturns struct {
		result1 *user.GetProfileByIdOutput
	}
	getProfileByIdReturnsOnCall map[int]struct {
		result1 *user.GetProfileByIdOutput
	}
	GetUserStub        func(context.Context, *user.GetUserInput) *user.GetUserOutput
	getUserMutex       sync.RWMutex
	getUserArgsForCall []struct {
		arg1 context.Context
		arg2 *user.GetUserInput
	}
	getUserReturns struct {
		result1 *user.GetUserOutput
	}
	getUserReturnsOnCall map[int]struct {
		result1 *user.GetUserOutput
	}
	GrantPermissionSystemStub        func(context.Context, *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput
	grantPermissionSystemMutex       sync.RWMutex
	grantPermissionSystemArgsForCall []struct {
		arg1 context.Context
		arg2 *workflow.GrantPermissionInput
	}
	grantPermissionSystemReturns struct {
		result1 *workflow.GrantPermissionOutput
	}
	grantPermissionSystemReturnsOnCall map[int]struct {
		result1 *workflow.GrantPermissionOutput
	}
	ListUsersStub        func(context.Context, *user.ListUsersInput) *user.ListUsersOutput
	listUsersMutex       sync.RWMutex
	listUsersArgsForCall []struct {
		arg1 context.Context
		arg2 *user.ListUsersInput
	}
	listUsersReturns struct {
		result1 *user.ListUsersOutput
	}
	listUsersReturnsOnCall map[int]struct {
		result1 *user.ListUsersOutput
	}
	LoginStub        func(context.Context, *user.LoginInput) *user.LoginOutput
	loginMutex       sync.RWMutex
	loginArgsForCall []struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}
	loginReturns struct {
		result1 *user.LoginOutput
	}
	loginReturnsOnCall map[int]struct {
		result1 *user.LoginOutput
	}
	LogoutStub        func(context.Context, *user.LogoutInput) *user.LogoutOutput
	logoutMutex       sync.RWMutex
	logoutArgsForCall []struct {
		arg1 context.Context
		arg2 *user.LogoutInput
	}
	logoutReturns struct {
		result1 *user.LogoutOutput
	}
	logoutReturnsOnCall map[int]struct {
		result1 *user.LogoutOutput
	}
	RefreshStub        func(context.Context, *user.RefreshInput) *user.RefreshOutput
	refreshMutex       sync.RWMutex
	refreshArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RefreshInput
	}
	refreshReturns struct {
		result1 *user.RefreshOutput
	}
	refreshReturnsOnCall map[int]struct {
		result1 *user.RefreshOutput
	}
	RegisterStub        func(context.Context, *user.RegisterInput) *user.RegisterOutput
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}
	registerReturns struct {
		result1 *user.RegisterOutput
	}
	registerReturnsOnCall map[int]struct {
		result1 *user.RegisterOutput
	}
	RegisterUserStub        func(context.Context, *workflow.RegisterUserInput) *workflow.RegisterUserOutput
	registerUserMutex       sync.RWMutex
	registerUserArgsForCall []struct {
		arg1 context.Context
		arg2 *workflow.RegisterUserInput
	}
	registerUserReturns struct {
		result1 *workflow.RegisterUserOutput
	}
	registerUserReturnsOnCall map[int]struct {
		result1 *workflow.RegisterUserOutput
	}
	RemovePermissionFromRoleStub        func(context.Context, *user.RemovePermissionFromRoleInput) *user.RemovePermissionFromRoleOutput
	removePermissionFromRoleMutex       sync.RWMutex
	removePermissionFromRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *user.RemovePermissionFromRoleInput
	}
	removePermissionFromRoleReturns struct {
		result1 *user.RemovePermissionFromRoleOutput
	}
	removePermissionFromRoleReturnsOnCall map[int]struct {
		result1 *user.RemovePermissionFromRoleOutput
	}
	ResetPasswordStub        func(context.Context, *user.ResetPasswordInput) *user.ResetPasswordOutput
	resetPasswordMutex       sync.RWMutex
	resetPasswordArgsForCall []struct {
		arg1 context.Context
		arg2 *user.ResetPasswordInput
	}
	resetPasswordReturns struct {
		result1 *user.ResetPasswordOutput
	}
	resetPasswordReturnsOnCall map[int]struct {
		result1 *user.ResetPasswordOutput
	}
	SendVerificationEmailStub        func(context.Context, *user.SendVerificationEmailInput) *user.SendVerificationEmailOutput
	sendVerificationEmailMutex       sync.RWMutex
	sendVerificationEmailArgsForCall []struct {
		arg1 context.Context
		arg2 *user.SendVerificationEmailInput
	}
	sendVerificationEmailReturns struct {
		result1 *user.SendVerificationEmailOutput
	}
	sendVerificationEmailReturnsOnCall map[int]struct {
		result1 *user.SendVerificationEmailOutput
	}
	UnassignRoleStub        func(context.Context, *user.UnassignRoleInput) *user.UnassignRoleOutput
	unassignRoleMutex       sync.RWMutex
	unassignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UnassignRoleInput
	}
	unassignRoleReturns struct {
		result1 *user.UnassignRoleOutput
	}
	unassignRoleReturnsOnCall map[int]struct {
		result1 *user.UnassignRoleOutput
	}
	UpdatePasswordStub        func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput
	updatePasswordMutex       sync.RWMutex
	updatePasswordArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}
	updatePasswordReturns struct {
		result1 *user.UpdatePasswordOutput
	}
	updatePasswordReturnsOnCall map[int]struct {
		result1 *user.UpdatePasswordOutput
	}
	UpdateUserStatusStub        func(context.Context, *user.UpdateUserStatusInput) *user.UpdateUserStatusOutput
	updateUserStatusMutex       sync.RWMutex
	updateUserStatusArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateUserStatusInput
	}
	updateUserStatusReturns struct {
		result1 *user.UpdateUserStatusOutput
	}
	updateUserStatusReturnsOnCall map[int]struct {
		result1 *user.UpdateUserStatusOutput
	}
	UpdateUsernameStub        func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput
	updateUsernameMutex       sync.RWMutex
	updateUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}
	updateUsernameReturns struct {
		result1 *user.UpdateUsernameOutput
	}
	updateUsernameReturnsOnCall map[int]struct {
		result1 *user.UpdateUsernameOutput
	}
	VerifyEmailStub        func(context.Context, *user.VerifyEmailInput) *user.VerifyEmailOutput
	verifyEmailMutex       sync.RWMutex
	verifyEmailArgsForCall []struct {
		arg1 context.Context
		arg2 *user.VerifyEmailInput
	}
	verifyEmailReturns struct {
		result1 *user.VerifyEmailOutput
	}
	verifyEmailReturnsOnCall map[int]struct {
		result1 *user.VerifyEmailOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) AssignPermissionToRole(arg1 context.Context, arg2 *user.AssignPermissionToRoleInput) *user.AssignPermissionToRoleOutput {
	fake.assignPermissionToRoleMutex.Lock()
	ret, specificReturn := fake.assignPermissionToRoleReturnsOnCall[len(fake.assignPermissionToRoleArgsForCall)]
	fake.assignPermissionToRoleArgsForCall = append(fake.assignPermissionToRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *user.AssignPermissionToRoleInput
	}{arg1, arg2})
	stub := fake.AssignPermissionToRoleStub
	fakeReturns := fake.assignPermissionToRoleReturns
	fake.recordInvocation("AssignPermissionToRole", []interface{}{arg1, arg2})
	fake.assignPermissionToRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AssignPermissionToRoleCallCount() int {
	fake.assignPermissionToRoleMutex.RLock()
	defer fake.assignPermissionToRoleMutex.RUnlock()
	return len(fake.assignPermissionToRoleArgsForCall)
}

func (fake *ServiceFake) AssignPermissionToRoleCalls(stub func(context.Context, *user.AssignPermissionToRoleInput) *user.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = stub
}

func (fake *ServiceFake) AssignPermissionToRoleArgsForCall(i int) (context.Context, *user.AssignPermissionToRoleInput) {
	fake.assignPermissionToRoleMutex.RLock()
	defer fake.assignPermissionToRoleMutex.RUnlock()
	argsForCall := fake.assignPermissionToRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AssignPermissionToRoleReturns(result1 *user.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = nil
	fake.assignPermissionToRoleReturns = struct {
		result1 *user.AssignPermissionToRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignPermissionToRoleReturnsOnCall(i int, result1 *user.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = nil
	if fake.assignPermissionToRoleReturnsOnCall == nil {
		fake.assignPermissionToRoleReturnsOnCall = make(map[int]struct {
			result1 *user.AssignPermissionToRoleOutput
		})
	}
	fake.assignPermissionToRoleReturnsOnCall[i] = struct {
		result1 *user.AssignPermissionToRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignRole(arg1 context.Context, arg2 *user.AssignRoleInput) *user.AssignRoleOutput {
	fake.assignRoleMutex.Lock()
	ret, specificReturn := fake.assignRoleReturnsOnCall[len(fake.assignRoleArgsForCall)]
	fake.assignRoleArgsForCall = append(fake.assignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *user.AssignRoleInput
	}{arg1, arg2})
	stub := fake.AssignRoleStub
	fakeReturns := fake.assignRoleReturns
	fake.recordInvocation("AssignRole", []interface{}{arg1, arg2})
	fake.assignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AssignRoleCallCount() int {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	return len(fake.assignRoleArgsForCall)
}

func (fake *ServiceFake) AssignRoleCalls(stub func(context.Context, *user.AssignRoleInput) *user.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = stub
}

func (fake *ServiceFake) AssignRoleArgsForCall(i int) (context.Context, *user.AssignRoleInput) {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	argsForCall := fake.assignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AssignRoleReturns(result1 *user.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	fake.assignRoleReturns = struct {
		result1 *user.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignRoleReturnsOnCall(i int, result1 *user.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	if fake.assignRoleReturnsOnCall == nil {
		fake.assignRoleReturnsOnCall = make(map[int]struct {
			result1 *user.AssignRoleOutput
		})
	}
	fake.assignRoleReturnsOnCall[i] = struct {
		result1 *user.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) DeleteUser(arg1 context.Context, arg2 *user.DeleteUserInput) *user.DeleteUserOutput {
	fake.deleteUserMutex.Lock()
	ret, specificReturn := fake.deleteUserReturnsOnCall[len(fake.deleteUserArgsForCall)]
	fake.deleteUserArgsForCall = append(fake.deleteUserArgsForCall, struct {
		arg1 context.Context
		arg2 *user.DeleteUserInput
	}{arg1, arg2})
	stub := fake.DeleteUserStub
	fakeReturns := fake.deleteUserReturns
	fake.recordInvocation("DeleteUser", []interface{}{arg1, arg2})
	fake.deleteUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) DeleteUserCallCount() int {
	fake.deleteUserMutex.RLock()
	defer fake.deleteUserMutex.RUnlock()
	return len(fake.deleteUserArgsForCall)
}

func (fake *ServiceFake) DeleteUserCalls(stub func(context.Context, *user.DeleteUserInput) *user.DeleteUserOutput) {
	fake.deleteUserMutex.Lock()
	defer fake.deleteUserMutex.Unlock()
	fake.DeleteUserStub = stub
}

func (fake *ServiceFake) DeleteUserArgsForCall(i int) (context.Context, *user.DeleteUserInput) {
	fake.deleteUserMutex.RLock()
	defer fake.deleteUserMutex.RUnlock()
	argsForCall := fake.deleteUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) DeleteUserReturns(result1 *user.DeleteUserOutput) {
	fake.deleteUserMutex.Lock()
	defer fake.deleteUserMutex.Unlock()
	fake.DeleteUserStub = nil
	fake.deleteUserReturns = struct {
		result1 *user.DeleteUserOutput
	}{result1}
}

func (fake *ServiceFake) DeleteUserReturnsOnCall(i int, result1 *user.DeleteUserOutput) {
	fake.deleteUserMutex.Lock()
	defer fake.deleteUserMutex.Unlock()
	fake.DeleteUserStub = nil
	if fake.deleteUserReturnsOnCall == nil {
		fake.deleteUserReturnsOnCall = make(map[int]struct {
			result1 *user.DeleteUserOutput
		})
	}
	fake.deleteUserReturnsOnCall[i] = struct {
		result1 *user.DeleteUserOutput
	}{result1}
}

func (fake *ServiceFake) DemoWorkflow(arg1 context.Context, arg2 *user.DemoWorkflowInput) *user.DemoWorkflowOutput {
	fake.demoWorkflowMutex.Lock()
	ret, specificReturn := fake.demoWorkflowReturnsOnCall[len(fake.demoWorkflowArgsForCall)]
	fake.demoWorkflowArgsForCall = append(fake.demoWorkflowArgsForCall, struct {
		arg1 context.Context
		arg2 *user.DemoWorkflowInput
	}{arg1, arg2})
	stub := fake.DemoWorkflowStub
	fakeReturns := fake.demoWorkflowReturns
	fake.recordInvocation("DemoWorkflow", []interface{}{arg1, arg2})
	fake.demoWorkflowMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) DemoWorkflowCallCount() int {
	fake.demoWorkflowMutex.RLock()
	defer fake.demoWorkflowMutex.RUnlock()
	return len(fake.demoWorkflowArgsForCall)
}

func (fake *ServiceFake) DemoWorkflowCalls(stub func(context.Context, *user.DemoWorkflowInput) *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = stub
}

func (fake *ServiceFake) DemoWorkflowArgsForCall(i int) (context.Context, *user.DemoWorkflowInput) {
	fake.demoWorkflowMutex.RLock()
	defer fake.demoWorkflowMutex.RUnlock()
	argsForCall := fake.demoWorkflowArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) DemoWorkflowReturns(result1 *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = nil
	fake.demoWorkflowReturns = struct {
		result1 *user.DemoWorkflowOutput
	}{result1}
}

func (fake *ServiceFake) DemoWorkflowReturnsOnCall(i int, result1 *user.DemoWorkflowOutput) {
	fake.demoWorkflowMutex.Lock()
	defer fake.demoWorkflowMutex.Unlock()
	fake.DemoWorkflowStub = nil
	if fake.demoWorkflowReturnsOnCall == nil {
		fake.demoWorkflowReturnsOnCall = make(map[int]struct {
			result1 *user.DemoWorkflowOutput
		})
	}
	fake.demoWorkflowReturnsOnCall[i] = struct {
		result1 *user.DemoWorkflowOutput
	}{result1}
}

func (fake *ServiceFake) ForgotPassword(arg1 context.Context, arg2 *user.ForgotPasswordInput) *user.ForgotPasswordOutput {
	fake.forgotPasswordMutex.Lock()
	ret, specificReturn := fake.forgotPasswordReturnsOnCall[len(fake.forgotPasswordArgsForCall)]
	fake.forgotPasswordArgsForCall = append(fake.forgotPasswordArgsForCall, struct {
		arg1 context.Context
		arg2 *user.ForgotPasswordInput
	}{arg1, arg2})
	stub := fake.ForgotPasswordStub
	fakeReturns := fake.forgotPasswordReturns
	fake.recordInvocation("ForgotPassword", []interface{}{arg1, arg2})
	fake.forgotPasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) ForgotPasswordCallCount() int {
	fake.forgotPasswordMutex.RLock()
	defer fake.forgotPasswordMutex.RUnlock()
	return len(fake.forgotPasswordArgsForCall)
}

func (fake *ServiceFake) ForgotPasswordCalls(stub func(context.Context, *user.ForgotPasswordInput) *user.ForgotPasswordOutput) {
	fake.forgotPasswordMutex.Lock()
	defer fake.forgotPasswordMutex.Unlock()
	fake.ForgotPasswordStub = stub
}

func (fake *ServiceFake) ForgotPasswordArgsForCall(i int) (context.Context, *user.ForgotPasswordInput) {
	fake.forgotPasswordMutex.RLock()
	defer fake.forgotPasswordMutex.RUnlock()
	argsForCall := fake.forgotPasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) ForgotPasswordReturns(result1 *user.ForgotPasswordOutput) {
	fake.forgotPasswordMutex.Lock()
	defer fake.forgotPasswordMutex.Unlock()
	fake.ForgotPasswordStub = nil
	fake.forgotPasswordReturns = struct {
		result1 *user.ForgotPasswordOutput
	}{result1}
}

func (fake *ServiceFake) ForgotPasswordReturnsOnCall(i int, result1 *user.ForgotPasswordOutput) {
	fake.forgotPasswordMutex.Lock()
	defer fake.forgotPasswordMutex.Unlock()
	fake.ForgotPasswordStub = nil
	if fake.forgotPasswordReturnsOnCall == nil {
		fake.forgotPasswordReturnsOnCall = make(map[int]struct {
			result1 *user.ForgotPasswordOutput
		})
	}
	fake.forgotPasswordReturnsOnCall[i] = struct {
		result1 *user.ForgotPasswordOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileById(arg1 context.Context, arg2 *user.GetProfileByIdInput) *user.GetProfileByIdOutput {
	fake.getProfileByIdMutex.Lock()
	ret, specificReturn := fake.getProfileByIdReturnsOnCall[len(fake.getProfileByIdArgsForCall)]
	fake.getProfileByIdArgsForCall = append(fake.getProfileByIdArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetProfileByIdInput
	}{arg1, arg2})
	stub := fake.GetProfileByIdStub
	fakeReturns := fake.getProfileByIdReturns
	fake.recordInvocation("GetProfileById", []interface{}{arg1, arg2})
	fake.getProfileByIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetProfileByIdCallCount() int {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	return len(fake.getProfileByIdArgsForCall)
}

func (fake *ServiceFake) GetProfileByIdCalls(stub func(context.Context, *user.GetProfileByIdInput) *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = stub
}

func (fake *ServiceFake) GetProfileByIdArgsForCall(i int) (context.Context, *user.GetProfileByIdInput) {
	fake.getProfileByIdMutex.RLock()
	defer fake.getProfileByIdMutex.RUnlock()
	argsForCall := fake.getProfileByIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetProfileByIdReturns(result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	fake.getProfileByIdReturns = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetProfileByIdReturnsOnCall(i int, result1 *user.GetProfileByIdOutput) {
	fake.getProfileByIdMutex.Lock()
	defer fake.getProfileByIdMutex.Unlock()
	fake.GetProfileByIdStub = nil
	if fake.getProfileByIdReturnsOnCall == nil {
		fake.getProfileByIdReturnsOnCall = make(map[int]struct {
			result1 *user.GetProfileByIdOutput
		})
	}
	fake.getProfileByIdReturnsOnCall[i] = struct {
		result1 *user.GetProfileByIdOutput
	}{result1}
}

func (fake *ServiceFake) GetUser(arg1 context.Context, arg2 *user.GetUserInput) *user.GetUserOutput {
	fake.getUserMutex.Lock()
	ret, specificReturn := fake.getUserReturnsOnCall[len(fake.getUserArgsForCall)]
	fake.getUserArgsForCall = append(fake.getUserArgsForCall, struct {
		arg1 context.Context
		arg2 *user.GetUserInput
	}{arg1, arg2})
	stub := fake.GetUserStub
	fakeReturns := fake.getUserReturns
	fake.recordInvocation("GetUser", []interface{}{arg1, arg2})
	fake.getUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GetUserCallCount() int {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	return len(fake.getUserArgsForCall)
}

func (fake *ServiceFake) GetUserCalls(stub func(context.Context, *user.GetUserInput) *user.GetUserOutput) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = stub
}

func (fake *ServiceFake) GetUserArgsForCall(i int) (context.Context, *user.GetUserInput) {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	argsForCall := fake.getUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GetUserReturns(result1 *user.GetUserOutput) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	fake.getUserReturns = struct {
		result1 *user.GetUserOutput
	}{result1}
}

func (fake *ServiceFake) GetUserReturnsOnCall(i int, result1 *user.GetUserOutput) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	if fake.getUserReturnsOnCall == nil {
		fake.getUserReturnsOnCall = make(map[int]struct {
			result1 *user.GetUserOutput
		})
	}
	fake.getUserReturnsOnCall[i] = struct {
		result1 *user.GetUserOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionSystem(arg1 context.Context, arg2 *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput {
	fake.grantPermissionSystemMutex.Lock()
	ret, specificReturn := fake.grantPermissionSystemReturnsOnCall[len(fake.grantPermissionSystemArgsForCall)]
	fake.grantPermissionSystemArgsForCall = append(fake.grantPermissionSystemArgsForCall, struct {
		arg1 context.Context
		arg2 *workflow.GrantPermissionInput
	}{arg1, arg2})
	stub := fake.GrantPermissionSystemStub
	fakeReturns := fake.grantPermissionSystemReturns
	fake.recordInvocation("GrantPermissionSystem", []interface{}{arg1, arg2})
	fake.grantPermissionSystemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GrantPermissionSystemCallCount() int {
	fake.grantPermissionSystemMutex.RLock()
	defer fake.grantPermissionSystemMutex.RUnlock()
	return len(fake.grantPermissionSystemArgsForCall)
}

func (fake *ServiceFake) GrantPermissionSystemCalls(stub func(context.Context, *workflow.GrantPermissionInput) *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = stub
}

func (fake *ServiceFake) GrantPermissionSystemArgsForCall(i int) (context.Context, *workflow.GrantPermissionInput) {
	fake.grantPermissionSystemMutex.RLock()
	defer fake.grantPermissionSystemMutex.RUnlock()
	argsForCall := fake.grantPermissionSystemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GrantPermissionSystemReturns(result1 *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = nil
	fake.grantPermissionSystemReturns = struct {
		result1 *workflow.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionSystemReturnsOnCall(i int, result1 *workflow.GrantPermissionOutput) {
	fake.grantPermissionSystemMutex.Lock()
	defer fake.grantPermissionSystemMutex.Unlock()
	fake.GrantPermissionSystemStub = nil
	if fake.grantPermissionSystemReturnsOnCall == nil {
		fake.grantPermissionSystemReturnsOnCall = make(map[int]struct {
			result1 *workflow.GrantPermissionOutput
		})
	}
	fake.grantPermissionSystemReturnsOnCall[i] = struct {
		result1 *workflow.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) ListUsers(arg1 context.Context, arg2 *user.ListUsersInput) *user.ListUsersOutput {
	fake.listUsersMutex.Lock()
	ret, specificReturn := fake.listUsersReturnsOnCall[len(fake.listUsersArgsForCall)]
	fake.listUsersArgsForCall = append(fake.listUsersArgsForCall, struct {
		arg1 context.Context
		arg2 *user.ListUsersInput
	}{arg1, arg2})
	stub := fake.ListUsersStub
	fakeReturns := fake.listUsersReturns
	fake.recordInvocation("ListUsers", []interface{}{arg1, arg2})
	fake.listUsersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) ListUsersCallCount() int {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	return len(fake.listUsersArgsForCall)
}

func (fake *ServiceFake) ListUsersCalls(stub func(context.Context, *user.ListUsersInput) *user.ListUsersOutput) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = stub
}

func (fake *ServiceFake) ListUsersArgsForCall(i int) (context.Context, *user.ListUsersInput) {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	argsForCall := fake.listUsersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) ListUsersReturns(result1 *user.ListUsersOutput) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	fake.listUsersReturns = struct {
		result1 *user.ListUsersOutput
	}{result1}
}

func (fake *ServiceFake) ListUsersReturnsOnCall(i int, result1 *user.ListUsersOutput) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	if fake.listUsersReturnsOnCall == nil {
		fake.listUsersReturnsOnCall = make(map[int]struct {
			result1 *user.ListUsersOutput
		})
	}
	fake.listUsersReturnsOnCall[i] = struct {
		result1 *user.ListUsersOutput
	}{result1}
}

func (fake *ServiceFake) Login(arg1 context.Context, arg2 *user.LoginInput) *user.LoginOutput {
	fake.loginMutex.Lock()
	ret, specificReturn := fake.loginReturnsOnCall[len(fake.loginArgsForCall)]
	fake.loginArgsForCall = append(fake.loginArgsForCall, struct {
		arg1 context.Context
		arg2 *user.LoginInput
	}{arg1, arg2})
	stub := fake.LoginStub
	fakeReturns := fake.loginReturns
	fake.recordInvocation("Login", []interface{}{arg1, arg2})
	fake.loginMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) LoginCallCount() int {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	return len(fake.loginArgsForCall)
}

func (fake *ServiceFake) LoginCalls(stub func(context.Context, *user.LoginInput) *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = stub
}

func (fake *ServiceFake) LoginArgsForCall(i int) (context.Context, *user.LoginInput) {
	fake.loginMutex.RLock()
	defer fake.loginMutex.RUnlock()
	argsForCall := fake.loginArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) LoginReturns(result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	fake.loginReturns = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) LoginReturnsOnCall(i int, result1 *user.LoginOutput) {
	fake.loginMutex.Lock()
	defer fake.loginMutex.Unlock()
	fake.LoginStub = nil
	if fake.loginReturnsOnCall == nil {
		fake.loginReturnsOnCall = make(map[int]struct {
			result1 *user.LoginOutput
		})
	}
	fake.loginReturnsOnCall[i] = struct {
		result1 *user.LoginOutput
	}{result1}
}

func (fake *ServiceFake) Logout(arg1 context.Context, arg2 *user.LogoutInput) *user.LogoutOutput {
	fake.logoutMutex.Lock()
	ret, specificReturn := fake.logoutReturnsOnCall[len(fake.logoutArgsForCall)]
	fake.logoutArgsForCall = append(fake.logoutArgsForCall, struct {
		arg1 context.Context
		arg2 *user.LogoutInput
	}{arg1, arg2})
	stub := fake.LogoutStub
	fakeReturns := fake.logoutReturns
	fake.recordInvocation("Logout", []interface{}{arg1, arg2})
	fake.logoutMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) LogoutCallCount() int {
	fake.logoutMutex.RLock()
	defer fake.logoutMutex.RUnlock()
	return len(fake.logoutArgsForCall)
}

func (fake *ServiceFake) LogoutCalls(stub func(context.Context, *user.LogoutInput) *user.LogoutOutput) {
	fake.logoutMutex.Lock()
	defer fake.logoutMutex.Unlock()
	fake.LogoutStub = stub
}

func (fake *ServiceFake) LogoutArgsForCall(i int) (context.Context, *user.LogoutInput) {
	fake.logoutMutex.RLock()
	defer fake.logoutMutex.RUnlock()
	argsForCall := fake.logoutArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) LogoutReturns(result1 *user.LogoutOutput) {
	fake.logoutMutex.Lock()
	defer fake.logoutMutex.Unlock()
	fake.LogoutStub = nil
	fake.logoutReturns = struct {
		result1 *user.LogoutOutput
	}{result1}
}

func (fake *ServiceFake) LogoutReturnsOnCall(i int, result1 *user.LogoutOutput) {
	fake.logoutMutex.Lock()
	defer fake.logoutMutex.Unlock()
	fake.LogoutStub = nil
	if fake.logoutReturnsOnCall == nil {
		fake.logoutReturnsOnCall = make(map[int]struct {
			result1 *user.LogoutOutput
		})
	}
	fake.logoutReturnsOnCall[i] = struct {
		result1 *user.LogoutOutput
	}{result1}
}

func (fake *ServiceFake) Refresh(arg1 context.Context, arg2 *user.RefreshInput) *user.RefreshOutput {
	fake.refreshMutex.Lock()
	ret, specificReturn := fake.refreshReturnsOnCall[len(fake.refreshArgsForCall)]
	fake.refreshArgsForCall = append(fake.refreshArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RefreshInput
	}{arg1, arg2})
	stub := fake.RefreshStub
	fakeReturns := fake.refreshReturns
	fake.recordInvocation("Refresh", []interface{}{arg1, arg2})
	fake.refreshMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RefreshCallCount() int {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	return len(fake.refreshArgsForCall)
}

func (fake *ServiceFake) RefreshCalls(stub func(context.Context, *user.RefreshInput) *user.RefreshOutput) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = stub
}

func (fake *ServiceFake) RefreshArgsForCall(i int) (context.Context, *user.RefreshInput) {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	argsForCall := fake.refreshArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RefreshReturns(result1 *user.RefreshOutput) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	fake.refreshReturns = struct {
		result1 *user.RefreshOutput
	}{result1}
}

func (fake *ServiceFake) RefreshReturnsOnCall(i int, result1 *user.RefreshOutput) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	if fake.refreshReturnsOnCall == nil {
		fake.refreshReturnsOnCall = make(map[int]struct {
			result1 *user.RefreshOutput
		})
	}
	fake.refreshReturnsOnCall[i] = struct {
		result1 *user.RefreshOutput
	}{result1}
}

func (fake *ServiceFake) Register(arg1 context.Context, arg2 *user.RegisterInput) *user.RegisterOutput {
	fake.registerMutex.Lock()
	ret, specificReturn := fake.registerReturnsOnCall[len(fake.registerArgsForCall)]
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RegisterInput
	}{arg1, arg2})
	stub := fake.RegisterStub
	fakeReturns := fake.registerReturns
	fake.recordInvocation("Register", []interface{}{arg1, arg2})
	fake.registerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *ServiceFake) RegisterCalls(stub func(context.Context, *user.RegisterInput) *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = stub
}

func (fake *ServiceFake) RegisterArgsForCall(i int) (context.Context, *user.RegisterInput) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	argsForCall := fake.registerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RegisterReturns(result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	fake.registerReturns = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) RegisterReturnsOnCall(i int, result1 *user.RegisterOutput) {
	fake.registerMutex.Lock()
	defer fake.registerMutex.Unlock()
	fake.RegisterStub = nil
	if fake.registerReturnsOnCall == nil {
		fake.registerReturnsOnCall = make(map[int]struct {
			result1 *user.RegisterOutput
		})
	}
	fake.registerReturnsOnCall[i] = struct {
		result1 *user.RegisterOutput
	}{result1}
}

func (fake *ServiceFake) RegisterUser(arg1 context.Context, arg2 *workflow.RegisterUserInput) *workflow.RegisterUserOutput {
	fake.registerUserMutex.Lock()
	ret, specificReturn := fake.registerUserReturnsOnCall[len(fake.registerUserArgsForCall)]
	fake.registerUserArgsForCall = append(fake.registerUserArgsForCall, struct {
		arg1 context.Context
		arg2 *workflow.RegisterUserInput
	}{arg1, arg2})
	stub := fake.RegisterUserStub
	fakeReturns := fake.registerUserReturns
	fake.recordInvocation("RegisterUser", []interface{}{arg1, arg2})
	fake.registerUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RegisterUserCallCount() int {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	return len(fake.registerUserArgsForCall)
}

func (fake *ServiceFake) RegisterUserCalls(stub func(context.Context, *workflow.RegisterUserInput) *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = stub
}

func (fake *ServiceFake) RegisterUserArgsForCall(i int) (context.Context, *workflow.RegisterUserInput) {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	argsForCall := fake.registerUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RegisterUserReturns(result1 *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = nil
	fake.registerUserReturns = struct {
		result1 *workflow.RegisterUserOutput
	}{result1}
}

func (fake *ServiceFake) RegisterUserReturnsOnCall(i int, result1 *workflow.RegisterUserOutput) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = nil
	if fake.registerUserReturnsOnCall == nil {
		fake.registerUserReturnsOnCall = make(map[int]struct {
			result1 *workflow.RegisterUserOutput
		})
	}
	fake.registerUserReturnsOnCall[i] = struct {
		result1 *workflow.RegisterUserOutput
	}{result1}
}

func (fake *ServiceFake) RemovePermissionFromRole(arg1 context.Context, arg2 *user.RemovePermissionFromRoleInput) *user.RemovePermissionFromRoleOutput {
	fake.removePermissionFromRoleMutex.Lock()
	ret, specificReturn := fake.removePermissionFromRoleReturnsOnCall[len(fake.removePermissionFromRoleArgsForCall)]
	fake.removePermissionFromRoleArgsForCall = append(fake.removePermissionFromRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *user.RemovePermissionFromRoleInput
	}{arg1, arg2})
	stub := fake.RemovePermissionFromRoleStub
	fakeReturns := fake.removePermissionFromRoleReturns
	fake.recordInvocation("RemovePermissionFromRole", []interface{}{arg1, arg2})
	fake.removePermissionFromRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RemovePermissionFromRoleCallCount() int {
	fake.removePermissionFromRoleMutex.RLock()
	defer fake.removePermissionFromRoleMutex.RUnlock()
	return len(fake.removePermissionFromRoleArgsForCall)
}

func (fake *ServiceFake) RemovePermissionFromRoleCalls(stub func(context.Context, *user.RemovePermissionFromRoleInput) *user.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = stub
}

func (fake *ServiceFake) RemovePermissionFromRoleArgsForCall(i int) (context.Context, *user.RemovePermissionFromRoleInput) {
	fake.removePermissionFromRoleMutex.RLock()
	defer fake.removePermissionFromRoleMutex.RUnlock()
	argsForCall := fake.removePermissionFromRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RemovePermissionFromRoleReturns(result1 *user.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = nil
	fake.removePermissionFromRoleReturns = struct {
		result1 *user.RemovePermissionFromRoleOutput
	}{result1}
}

func (fake *ServiceFake) RemovePermissionFromRoleReturnsOnCall(i int, result1 *user.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = nil
	if fake.removePermissionFromRoleReturnsOnCall == nil {
		fake.removePermissionFromRoleReturnsOnCall = make(map[int]struct {
			result1 *user.RemovePermissionFromRoleOutput
		})
	}
	fake.removePermissionFromRoleReturnsOnCall[i] = struct {
		result1 *user.RemovePermissionFromRoleOutput
	}{result1}
}

func (fake *ServiceFake) ResetPassword(arg1 context.Context, arg2 *user.ResetPasswordInput) *user.ResetPasswordOutput {
	fake.resetPasswordMutex.Lock()
	ret, specificReturn := fake.resetPasswordReturnsOnCall[len(fake.resetPasswordArgsForCall)]
	fake.resetPasswordArgsForCall = append(fake.resetPasswordArgsForCall, struct {
		arg1 context.Context
		arg2 *user.ResetPasswordInput
	}{arg1, arg2})
	stub := fake.ResetPasswordStub
	fakeReturns := fake.resetPasswordReturns
	fake.recordInvocation("ResetPassword", []interface{}{arg1, arg2})
	fake.resetPasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) ResetPasswordCallCount() int {
	fake.resetPasswordMutex.RLock()
	defer fake.resetPasswordMutex.RUnlock()
	return len(fake.resetPasswordArgsForCall)
}

func (fake *ServiceFake) ResetPasswordCalls(stub func(context.Context, *user.ResetPasswordInput) *user.ResetPasswordOutput) {
	fake.resetPasswordMutex.Lock()
	defer fake.resetPasswordMutex.Unlock()
	fake.ResetPasswordStub = stub
}

func (fake *ServiceFake) ResetPasswordArgsForCall(i int) (context.Context, *user.ResetPasswordInput) {
	fake.resetPasswordMutex.RLock()
	defer fake.resetPasswordMutex.RUnlock()
	argsForCall := fake.resetPasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) ResetPasswordReturns(result1 *user.ResetPasswordOutput) {
	fake.resetPasswordMutex.Lock()
	defer fake.resetPasswordMutex.Unlock()
	fake.ResetPasswordStub = nil
	fake.resetPasswordReturns = struct {
		result1 *user.ResetPasswordOutput
	}{result1}
}

func (fake *ServiceFake) ResetPasswordReturnsOnCall(i int, result1 *user.ResetPasswordOutput) {
	fake.resetPasswordMutex.Lock()
	defer fake.resetPasswordMutex.Unlock()
	fake.ResetPasswordStub = nil
	if fake.resetPasswordReturnsOnCall == nil {
		fake.resetPasswordReturnsOnCall = make(map[int]struct {
			result1 *user.ResetPasswordOutput
		})
	}
	fake.resetPasswordReturnsOnCall[i] = struct {
		result1 *user.ResetPasswordOutput
	}{result1}
}

func (fake *ServiceFake) SendVerificationEmail(arg1 context.Context, arg2 *user.SendVerificationEmailInput) *user.SendVerificationEmailOutput {
	fake.sendVerificationEmailMutex.Lock()
	ret, specificReturn := fake.sendVerificationEmailReturnsOnCall[len(fake.sendVerificationEmailArgsForCall)]
	fake.sendVerificationEmailArgsForCall = append(fake.sendVerificationEmailArgsForCall, struct {
		arg1 context.Context
		arg2 *user.SendVerificationEmailInput
	}{arg1, arg2})
	stub := fake.SendVerificationEmailStub
	fakeReturns := fake.sendVerificationEmailReturns
	fake.recordInvocation("SendVerificationEmail", []interface{}{arg1, arg2})
	fake.sendVerificationEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) SendVerificationEmailCallCount() int {
	fake.sendVerificationEmailMutex.RLock()
	defer fake.sendVerificationEmailMutex.RUnlock()
	return len(fake.sendVerificationEmailArgsForCall)
}

func (fake *ServiceFake) SendVerificationEmailCalls(stub func(context.Context, *user.SendVerificationEmailInput) *user.SendVerificationEmailOutput) {
	fake.sendVerificationEmailMutex.Lock()
	defer fake.sendVerificationEmailMutex.Unlock()
	fake.SendVerificationEmailStub = stub
}

func (fake *ServiceFake) SendVerificationEmailArgsForCall(i int) (context.Context, *user.SendVerificationEmailInput) {
	fake.sendVerificationEmailMutex.RLock()
	defer fake.sendVerificationEmailMutex.RUnlock()
	argsForCall := fake.sendVerificationEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) SendVerificationEmailReturns(result1 *user.SendVerificationEmailOutput) {
	fake.sendVerificationEmailMutex.Lock()
	defer fake.sendVerificationEmailMutex.Unlock()
	fake.SendVerificationEmailStub = nil
	fake.sendVerificationEmailReturns = struct {
		result1 *user.SendVerificationEmailOutput
	}{result1}
}

func (fake *ServiceFake) SendVerificationEmailReturnsOnCall(i int, result1 *user.SendVerificationEmailOutput) {
	fake.sendVerificationEmailMutex.Lock()
	defer fake.sendVerificationEmailMutex.Unlock()
	fake.SendVerificationEmailStub = nil
	if fake.sendVerificationEmailReturnsOnCall == nil {
		fake.sendVerificationEmailReturnsOnCall = make(map[int]struct {
			result1 *user.SendVerificationEmailOutput
		})
	}
	fake.sendVerificationEmailReturnsOnCall[i] = struct {
		result1 *user.SendVerificationEmailOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRole(arg1 context.Context, arg2 *user.UnassignRoleInput) *user.UnassignRoleOutput {
	fake.unassignRoleMutex.Lock()
	ret, specificReturn := fake.unassignRoleReturnsOnCall[len(fake.unassignRoleArgsForCall)]
	fake.unassignRoleArgsForCall = append(fake.unassignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UnassignRoleInput
	}{arg1, arg2})
	stub := fake.UnassignRoleStub
	fakeReturns := fake.unassignRoleReturns
	fake.recordInvocation("UnassignRole", []interface{}{arg1, arg2})
	fake.unassignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UnassignRoleCallCount() int {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	return len(fake.unassignRoleArgsForCall)
}

func (fake *ServiceFake) UnassignRoleCalls(stub func(context.Context, *user.UnassignRoleInput) *user.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = stub
}

func (fake *ServiceFake) UnassignRoleArgsForCall(i int) (context.Context, *user.UnassignRoleInput) {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	argsForCall := fake.unassignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UnassignRoleReturns(result1 *user.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	fake.unassignRoleReturns = struct {
		result1 *user.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRoleReturnsOnCall(i int, result1 *user.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	if fake.unassignRoleReturnsOnCall == nil {
		fake.unassignRoleReturnsOnCall = make(map[int]struct {
			result1 *user.UnassignRoleOutput
		})
	}
	fake.unassignRoleReturnsOnCall[i] = struct {
		result1 *user.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePassword(arg1 context.Context, arg2 *user.UpdatePasswordInput) *user.UpdatePasswordOutput {
	fake.updatePasswordMutex.Lock()
	ret, specificReturn := fake.updatePasswordReturnsOnCall[len(fake.updatePasswordArgsForCall)]
	fake.updatePasswordArgsForCall = append(fake.updatePasswordArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdatePasswordInput
	}{arg1, arg2})
	stub := fake.UpdatePasswordStub
	fakeReturns := fake.updatePasswordReturns
	fake.recordInvocation("UpdatePassword", []interface{}{arg1, arg2})
	fake.updatePasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdatePasswordCallCount() int {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	return len(fake.updatePasswordArgsForCall)
}

func (fake *ServiceFake) UpdatePasswordCalls(stub func(context.Context, *user.UpdatePasswordInput) *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = stub
}

func (fake *ServiceFake) UpdatePasswordArgsForCall(i int) (context.Context, *user.UpdatePasswordInput) {
	fake.updatePasswordMutex.RLock()
	defer fake.updatePasswordMutex.RUnlock()
	argsForCall := fake.updatePasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdatePasswordReturns(result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	fake.updatePasswordReturns = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdatePasswordReturnsOnCall(i int, result1 *user.UpdatePasswordOutput) {
	fake.updatePasswordMutex.Lock()
	defer fake.updatePasswordMutex.Unlock()
	fake.UpdatePasswordStub = nil
	if fake.updatePasswordReturnsOnCall == nil {
		fake.updatePasswordReturnsOnCall = make(map[int]struct {
			result1 *user.UpdatePasswordOutput
		})
	}
	fake.updatePasswordReturnsOnCall[i] = struct {
		result1 *user.UpdatePasswordOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUserStatus(arg1 context.Context, arg2 *user.UpdateUserStatusInput) *user.UpdateUserStatusOutput {
	fake.updateUserStatusMutex.Lock()
	ret, specificReturn := fake.updateUserStatusReturnsOnCall[len(fake.updateUserStatusArgsForCall)]
	fake.updateUserStatusArgsForCall = append(fake.updateUserStatusArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateUserStatusInput
	}{arg1, arg2})
	stub := fake.UpdateUserStatusStub
	fakeReturns := fake.updateUserStatusReturns
	fake.recordInvocation("UpdateUserStatus", []interface{}{arg1, arg2})
	fake.updateUserStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateUserStatusCallCount() int {
	fake.updateUserStatusMutex.RLock()
	defer fake.updateUserStatusMutex.RUnlock()
	return len(fake.updateUserStatusArgsForCall)
}

func (fake *ServiceFake) UpdateUserStatusCalls(stub func(context.Context, *user.UpdateUserStatusInput) *user.UpdateUserStatusOutput) {
	fake.updateUserStatusMutex.Lock()
	defer fake.updateUserStatusMutex.Unlock()
	fake.UpdateUserStatusStub = stub
}

func (fake *ServiceFake) UpdateUserStatusArgsForCall(i int) (context.Context, *user.UpdateUserStatusInput) {
	fake.updateUserStatusMutex.RLock()
	defer fake.updateUserStatusMutex.RUnlock()
	argsForCall := fake.updateUserStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateUserStatusReturns(result1 *user.UpdateUserStatusOutput) {
	fake.updateUserStatusMutex.Lock()
	defer fake.updateUserStatusMutex.Unlock()
	fake.UpdateUserStatusStub = nil
	fake.updateUserStatusReturns = struct {
		result1 *user.UpdateUserStatusOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUserStatusReturnsOnCall(i int, result1 *user.UpdateUserStatusOutput) {
	fake.updateUserStatusMutex.Lock()
	defer fake.updateUserStatusMutex.Unlock()
	fake.UpdateUserStatusStub = nil
	if fake.updateUserStatusReturnsOnCall == nil {
		fake.updateUserStatusReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateUserStatusOutput
		})
	}
	fake.updateUserStatusReturnsOnCall[i] = struct {
		result1 *user.UpdateUserStatusOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsername(arg1 context.Context, arg2 *user.UpdateUsernameInput) *user.UpdateUsernameOutput {
	fake.updateUsernameMutex.Lock()
	ret, specificReturn := fake.updateUsernameReturnsOnCall[len(fake.updateUsernameArgsForCall)]
	fake.updateUsernameArgsForCall = append(fake.updateUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 *user.UpdateUsernameInput
	}{arg1, arg2})
	stub := fake.UpdateUsernameStub
	fakeReturns := fake.updateUsernameReturns
	fake.recordInvocation("UpdateUsername", []interface{}{arg1, arg2})
	fake.updateUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UpdateUsernameCallCount() int {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	return len(fake.updateUsernameArgsForCall)
}

func (fake *ServiceFake) UpdateUsernameCalls(stub func(context.Context, *user.UpdateUsernameInput) *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = stub
}

func (fake *ServiceFake) UpdateUsernameArgsForCall(i int) (context.Context, *user.UpdateUsernameInput) {
	fake.updateUsernameMutex.RLock()
	defer fake.updateUsernameMutex.RUnlock()
	argsForCall := fake.updateUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UpdateUsernameReturns(result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	fake.updateUsernameReturns = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) UpdateUsernameReturnsOnCall(i int, result1 *user.UpdateUsernameOutput) {
	fake.updateUsernameMutex.Lock()
	defer fake.updateUsernameMutex.Unlock()
	fake.UpdateUsernameStub = nil
	if fake.updateUsernameReturnsOnCall == nil {
		fake.updateUsernameReturnsOnCall = make(map[int]struct {
			result1 *user.UpdateUsernameOutput
		})
	}
	fake.updateUsernameReturnsOnCall[i] = struct {
		result1 *user.UpdateUsernameOutput
	}{result1}
}

func (fake *ServiceFake) VerifyEmail(arg1 context.Context, arg2 *user.VerifyEmailInput) *user.VerifyEmailOutput {
	fake.verifyEmailMutex.Lock()
	ret, specificReturn := fake.verifyEmailReturnsOnCall[len(fake.verifyEmailArgsForCall)]
	fake.verifyEmailArgsForCall = append(fake.verifyEmailArgsForCall, struct {
		arg1 context.Context
		arg2 *user.VerifyEmailInput
	}{arg1, arg2})
	stub := fake.VerifyEmailStub
	fakeReturns := fake.verifyEmailReturns
	fake.recordInvocation("VerifyEmail", []interface{}{arg1, arg2})
	fake.verifyEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) VerifyEmailCallCount() int {
	fake.verifyEmailMutex.RLock()
	defer fake.verifyEmailMutex.RUnlock()
	return len(fake.verifyEmailArgsForCall)
}

func (fake *ServiceFake) VerifyEmailCalls(stub func(context.Context, *user.VerifyEmailInput) *user.VerifyEmailOutput) {
	fake.verifyEmailMutex.Lock()
	defer fake.verifyEmailMutex.Unlock()
	fake.VerifyEmailStub = stub
}

func (fake *ServiceFake) VerifyEmailArgsForCall(i int) (context.Context, *user.VerifyEmailInput) {
	fake.verifyEmailMutex.RLock()
	defer fake.verifyEmailMutex.RUnlock()
	argsForCall := fake.verifyEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) VerifyEmailReturns(result1 *user.VerifyEmailOutput) {
	fake.verifyEmailMutex.Lock()
	defer fake.verifyEmailMutex.Unlock()
	fake.VerifyEmailStub = nil
	fake.verifyEmailReturns = struct {
		result1 *user.VerifyEmailOutput
	}{result1}
}

func (fake *ServiceFake) VerifyEmailReturnsOnCall(i int, result1 *user.VerifyEmailOutput) {
	fake.verifyEmailMutex.Lock()
	defer fake.verifyEmailMutex.Unlock()
	fake.VerifyEmailStub = nil
	if fake.verifyEmailReturnsOnCall == nil {
		fake.verifyEmailReturnsOnCall = make(map[int]struct {
			result1 *user.VerifyEmailOutput
		})
	}
	fake.verifyEmailReturnsOnCall[i] = struct {
		result1 *user.VerifyEmailOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ user.Service = new(ServiceFake)
