// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/permission"
)

type ServiceFake struct {
	AddRolePermissionStub        func(context.Context, *permission.AddRolePermissionInput) *permission.AddRolePermissionOutput
	addRolePermissionMutex       sync.RWMutex
	addRolePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.AddRolePermissionInput
	}
	addRolePermissionReturns struct {
		result1 *permission.AddRolePermissionOutput
	}
	addRolePermissionReturnsOnCall map[int]struct {
		result1 *permission.AddRolePermissionOutput
	}
	AssignRoleStub        func(context.Context, *permission.AssignRoleInput) *permission.AssignRoleOutput
	assignRoleMutex       sync.RWMutex
	assignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.AssignRoleInput
	}
	assignRoleReturns struct {
		result1 *permission.AssignRoleOutput
	}
	assignRoleReturnsOnCall map[int]struct {
		result1 *permission.AssignRoleOutput
	}
	CheckPermissionStub        func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput
	checkPermissionMutex       sync.RWMutex
	checkPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}
	checkPermissionReturns struct {
		result1 *permission.CheckPermissionOutput
	}
	checkPermissionReturnsOnCall map[int]struct {
		result1 *permission.CheckPermissionOutput
	}
	CreateRoleStub        func(context.Context, *permission.CreateRoleInput) *permission.CreateRoleOutput
	createRoleMutex       sync.RWMutex
	createRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.CreateRoleInput
	}
	createRoleReturns struct {
		result1 *permission.CreateRoleOutput
	}
	createRoleReturnsOnCall map[int]struct {
		result1 *permission.CreateRoleOutput
	}
	DeleteRoleStub        func(context.Context, *permission.DeleteRoleInput) *permission.DeleteRoleOutput
	deleteRoleMutex       sync.RWMutex
	deleteRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.DeleteRoleInput
	}
	deleteRoleReturns struct {
		result1 *permission.DeleteRoleOutput
	}
	deleteRoleReturnsOnCall map[int]struct {
		result1 *permission.DeleteRoleOutput
	}
	GrantPermissionStub        func(context.Context, *permission.GrantPermissionInput) *permission.GrantPermissionOutput
	grantPermissionMutex       sync.RWMutex
	grantPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.GrantPermissionInput
	}
	grantPermissionReturns struct {
		result1 *permission.GrantPermissionOutput
	}
	grantPermissionReturnsOnCall map[int]struct {
		result1 *permission.GrantPermissionOutput
	}
	ListUserPermissionsStub        func(context.Context, *permission.ListUserPermissionsInput) *permission.ListUserPermissionsOutput
	listUserPermissionsMutex       sync.RWMutex
	listUserPermissionsArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.ListUserPermissionsInput
	}
	listUserPermissionsReturns struct {
		result1 *permission.ListUserPermissionsOutput
	}
	listUserPermissionsReturnsOnCall map[int]struct {
		result1 *permission.ListUserPermissionsOutput
	}
	RemoveRolePermissionStub        func(context.Context, *permission.RemoveRolePermissionInput) *permission.RemoveRolePermissionOutput
	removeRolePermissionMutex       sync.RWMutex
	removeRolePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.RemoveRolePermissionInput
	}
	removeRolePermissionReturns struct {
		result1 *permission.RemoveRolePermissionOutput
	}
	removeRolePermissionReturnsOnCall map[int]struct {
		result1 *permission.RemoveRolePermissionOutput
	}
	RevokePermissionStub        func(context.Context, *permission.RevokePermissionInput) *permission.RevokePermissionOutput
	revokePermissionMutex       sync.RWMutex
	revokePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.RevokePermissionInput
	}
	revokePermissionReturns struct {
		result1 *permission.RevokePermissionOutput
	}
	revokePermissionReturnsOnCall map[int]struct {
		result1 *permission.RevokePermissionOutput
	}
	UnassignRoleStub        func(context.Context, *permission.UnassignRoleInput) *permission.UnassignRoleOutput
	unassignRoleMutex       sync.RWMutex
	unassignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.UnassignRoleInput
	}
	unassignRoleReturns struct {
		result1 *permission.UnassignRoleOutput
	}
	unassignRoleReturnsOnCall map[int]struct {
		result1 *permission.UnassignRoleOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) AddRolePermission(arg1 context.Context, arg2 *permission.AddRolePermissionInput) *permission.AddRolePermissionOutput {
	fake.addRolePermissionMutex.Lock()
	ret, specificReturn := fake.addRolePermissionReturnsOnCall[len(fake.addRolePermissionArgsForCall)]
	fake.addRolePermissionArgsForCall = append(fake.addRolePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.AddRolePermissionInput
	}{arg1, arg2})
	stub := fake.AddRolePermissionStub
	fakeReturns := fake.addRolePermissionReturns
	fake.recordInvocation("AddRolePermission", []interface{}{arg1, arg2})
	fake.addRolePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AddRolePermissionCallCount() int {
	fake.addRolePermissionMutex.RLock()
	defer fake.addRolePermissionMutex.RUnlock()
	return len(fake.addRolePermissionArgsForCall)
}

func (fake *ServiceFake) AddRolePermissionCalls(stub func(context.Context, *permission.AddRolePermissionInput) *permission.AddRolePermissionOutput) {
	fake.addRolePermissionMutex.Lock()
	defer fake.addRolePermissionMutex.Unlock()
	fake.AddRolePermissionStub = stub
}

func (fake *ServiceFake) AddRolePermissionArgsForCall(i int) (context.Context, *permission.AddRolePermissionInput) {
	fake.addRolePermissionMutex.RLock()
	defer fake.addRolePermissionMutex.RUnlock()
	argsForCall := fake.addRolePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AddRolePermissionReturns(result1 *permission.AddRolePermissionOutput) {
	fake.addRolePermissionMutex.Lock()
	defer fake.addRolePermissionMutex.Unlock()
	fake.AddRolePermissionStub = nil
	fake.addRolePermissionReturns = struct {
		result1 *permission.AddRolePermissionOutput
	}{result1}
}

func (fake *ServiceFake) AddRolePermissionReturnsOnCall(i int, result1 *permission.AddRolePermissionOutput) {
	fake.addRolePermissionMutex.Lock()
	defer fake.addRolePermissionMutex.Unlock()
	fake.AddRolePermissionStub = nil
	if fake.addRolePermissionReturnsOnCall == nil {
		fake.addRolePermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.AddRolePermissionOutput
		})
	}
	fake.addRolePermissionReturnsOnCall[i] = struct {
		result1 *permission.AddRolePermissionOutput
	}{result1}
}

func (fake *ServiceFake) AssignRole(arg1 context.Context, arg2 *permission.AssignRoleInput) *permission.AssignRoleOutput {
	fake.assignRoleMutex.Lock()
	ret, specificReturn := fake.assignRoleReturnsOnCall[len(fake.assignRoleArgsForCall)]
	fake.assignRoleArgsForCall = append(fake.assignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.AssignRoleInput
	}{arg1, arg2})
	stub := fake.AssignRoleStub
	fakeReturns := fake.assignRoleReturns
	fake.recordInvocation("AssignRole", []interface{}{arg1, arg2})
	fake.assignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AssignRoleCallCount() int {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	return len(fake.assignRoleArgsForCall)
}

func (fake *ServiceFake) AssignRoleCalls(stub func(context.Context, *permission.AssignRoleInput) *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = stub
}

func (fake *ServiceFake) AssignRoleArgsForCall(i int) (context.Context, *permission.AssignRoleInput) {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	argsForCall := fake.assignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AssignRoleReturns(result1 *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	fake.assignRoleReturns = struct {
		result1 *permission.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignRoleReturnsOnCall(i int, result1 *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	if fake.assignRoleReturnsOnCall == nil {
		fake.assignRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.AssignRoleOutput
		})
	}
	fake.assignRoleReturnsOnCall[i] = struct {
		result1 *permission.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) CheckPermission(arg1 context.Context, arg2 *permission.CheckPermissionInput) *permission.CheckPermissionOutput {
	fake.checkPermissionMutex.Lock()
	ret, specificReturn := fake.checkPermissionReturnsOnCall[len(fake.checkPermissionArgsForCall)]
	fake.checkPermissionArgsForCall = append(fake.checkPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}{arg1, arg2})
	stub := fake.CheckPermissionStub
	fakeReturns := fake.checkPermissionReturns
	fake.recordInvocation("CheckPermission", []interface{}{arg1, arg2})
	fake.checkPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) CheckPermissionCallCount() int {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	return len(fake.checkPermissionArgsForCall)
}

func (fake *ServiceFake) CheckPermissionCalls(stub func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = stub
}

func (fake *ServiceFake) CheckPermissionArgsForCall(i int) (context.Context, *permission.CheckPermissionInput) {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	argsForCall := fake.checkPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) CheckPermissionReturns(result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	fake.checkPermissionReturns = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) CheckPermissionReturnsOnCall(i int, result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	if fake.checkPermissionReturnsOnCall == nil {
		fake.checkPermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.CheckPermissionOutput
		})
	}
	fake.checkPermissionReturnsOnCall[i] = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) CreateRole(arg1 context.Context, arg2 *permission.CreateRoleInput) *permission.CreateRoleOutput {
	fake.createRoleMutex.Lock()
	ret, specificReturn := fake.createRoleReturnsOnCall[len(fake.createRoleArgsForCall)]
	fake.createRoleArgsForCall = append(fake.createRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.CreateRoleInput
	}{arg1, arg2})
	stub := fake.CreateRoleStub
	fakeReturns := fake.createRoleReturns
	fake.recordInvocation("CreateRole", []interface{}{arg1, arg2})
	fake.createRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) CreateRoleCallCount() int {
	fake.createRoleMutex.RLock()
	defer fake.createRoleMutex.RUnlock()
	return len(fake.createRoleArgsForCall)
}

func (fake *ServiceFake) CreateRoleCalls(stub func(context.Context, *permission.CreateRoleInput) *permission.CreateRoleOutput) {
	fake.createRoleMutex.Lock()
	defer fake.createRoleMutex.Unlock()
	fake.CreateRoleStub = stub
}

func (fake *ServiceFake) CreateRoleArgsForCall(i int) (context.Context, *permission.CreateRoleInput) {
	fake.createRoleMutex.RLock()
	defer fake.createRoleMutex.RUnlock()
	argsForCall := fake.createRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) CreateRoleReturns(result1 *permission.CreateRoleOutput) {
	fake.createRoleMutex.Lock()
	defer fake.createRoleMutex.Unlock()
	fake.CreateRoleStub = nil
	fake.createRoleReturns = struct {
		result1 *permission.CreateRoleOutput
	}{result1}
}

func (fake *ServiceFake) CreateRoleReturnsOnCall(i int, result1 *permission.CreateRoleOutput) {
	fake.createRoleMutex.Lock()
	defer fake.createRoleMutex.Unlock()
	fake.CreateRoleStub = nil
	if fake.createRoleReturnsOnCall == nil {
		fake.createRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.CreateRoleOutput
		})
	}
	fake.createRoleReturnsOnCall[i] = struct {
		result1 *permission.CreateRoleOutput
	}{result1}
}

func (fake *ServiceFake) DeleteRole(arg1 context.Context, arg2 *permission.DeleteRoleInput) *permission.DeleteRoleOutput {
	fake.deleteRoleMutex.Lock()
	ret, specificReturn := fake.deleteRoleReturnsOnCall[len(fake.deleteRoleArgsForCall)]
	fake.deleteRoleArgsForCall = append(fake.deleteRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.DeleteRoleInput
	}{arg1, arg2})
	stub := fake.DeleteRoleStub
	fakeReturns := fake.deleteRoleReturns
	fake.recordInvocation("DeleteRole", []interface{}{arg1, arg2})
	fake.deleteRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) DeleteRoleCallCount() int {
	fake.deleteRoleMutex.RLock()
	defer fake.deleteRoleMutex.RUnlock()
	return len(fake.deleteRoleArgsForCall)
}

func (fake *ServiceFake) DeleteRoleCalls(stub func(context.Context, *permission.DeleteRoleInput) *permission.DeleteRoleOutput) {
	fake.deleteRoleMutex.Lock()
	defer fake.deleteRoleMutex.Unlock()
	fake.DeleteRoleStub = stub
}

func (fake *ServiceFake) DeleteRoleArgsForCall(i int) (context.Context, *permission.DeleteRoleInput) {
	fake.deleteRoleMutex.RLock()
	defer fake.deleteRoleMutex.RUnlock()
	argsForCall := fake.deleteRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) DeleteRoleReturns(result1 *permission.DeleteRoleOutput) {
	fake.deleteRoleMutex.Lock()
	defer fake.deleteRoleMutex.Unlock()
	fake.DeleteRoleStub = nil
	fake.deleteRoleReturns = struct {
		result1 *permission.DeleteRoleOutput
	}{result1}
}

func (fake *ServiceFake) DeleteRoleReturnsOnCall(i int, result1 *permission.DeleteRoleOutput) {
	fake.deleteRoleMutex.Lock()
	defer fake.deleteRoleMutex.Unlock()
	fake.DeleteRoleStub = nil
	if fake.deleteRoleReturnsOnCall == nil {
		fake.deleteRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.DeleteRoleOutput
		})
	}
	fake.deleteRoleReturnsOnCall[i] = struct {
		result1 *permission.DeleteRoleOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermission(arg1 context.Context, arg2 *permission.GrantPermissionInput) *permission.GrantPermissionOutput {
	fake.grantPermissionMutex.Lock()
	ret, specificReturn := fake.grantPermissionReturnsOnCall[len(fake.grantPermissionArgsForCall)]
	fake.grantPermissionArgsForCall = append(fake.grantPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.GrantPermissionInput
	}{arg1, arg2})
	stub := fake.GrantPermissionStub
	fakeReturns := fake.grantPermissionReturns
	fake.recordInvocation("GrantPermission", []interface{}{arg1, arg2})
	fake.grantPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GrantPermissionCallCount() int {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	return len(fake.grantPermissionArgsForCall)
}

func (fake *ServiceFake) GrantPermissionCalls(stub func(context.Context, *permission.GrantPermissionInput) *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = stub
}

func (fake *ServiceFake) GrantPermissionArgsForCall(i int) (context.Context, *permission.GrantPermissionInput) {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	argsForCall := fake.grantPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GrantPermissionReturns(result1 *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	fake.grantPermissionReturns = struct {
		result1 *permission.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionReturnsOnCall(i int, result1 *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	if fake.grantPermissionReturnsOnCall == nil {
		fake.grantPermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.GrantPermissionOutput
		})
	}
	fake.grantPermissionReturnsOnCall[i] = struct {
		result1 *permission.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) ListUserPermissions(arg1 context.Context, arg2 *permission.ListUserPermissionsInput) *permission.ListUserPermissionsOutput {
	fake.listUserPermissionsMutex.Lock()
	ret, specificReturn := fake.listUserPermissionsReturnsOnCall[len(fake.listUserPermissionsArgsForCall)]
	fake.listUserPermissionsArgsForCall = append(fake.listUserPermissionsArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.ListUserPermissionsInput
	}{arg1, arg2})
	stub := fake.ListUserPermissionsStub
	fakeReturns := fake.listUserPermissionsReturns
	fake.recordInvocation("ListUserPermissions", []interface{}{arg1, arg2})
	fake.listUserPermissionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) ListUserPermissionsCallCount() int {
	fake.listUserPermissionsMutex.RLock()
	defer fake.listUserPermissionsMutex.RUnlock()
	return len(fake.listUserPermissionsArgsForCall)
}

func (fake *ServiceFake) ListUserPermissionsCalls(stub func(context.Context, *permission.ListUserPermissionsInput) *permission.ListUserPermissionsOutput) {
	fake.listUserPermissionsMutex.Lock()
	defer fake.listUserPermissionsMutex.Unlock()
	fake.ListUserPermissionsStub = stub
}

func (fake *ServiceFake) ListUserPermissionsArgsForCall(i int) (context.Context, *permission.ListUserPermissionsInput) {
	fake.listUserPermissionsMutex.RLock()
	defer fake.listUserPermissionsMutex.RUnlock()
	argsForCall := fake.listUserPermissionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) ListUserPermissionsReturns(result1 *permission.ListUserPermissionsOutput) {
	fake.listUserPermissionsMutex.Lock()
	defer fake.listUserPermissionsMutex.Unlock()
	fake.ListUserPermissionsStub = nil
	fake.listUserPermissionsReturns = struct {
		result1 *permission.ListUserPermissionsOutput
	}{result1}
}

func (fake *ServiceFake) ListUserPermissionsReturnsOnCall(i int, result1 *permission.ListUserPermissionsOutput) {
	fake.listUserPermissionsMutex.Lock()
	defer fake.listUserPermissionsMutex.Unlock()
	fake.ListUserPermissionsStub = nil
	if fake.listUserPermissionsReturnsOnCall == nil {
		fake.listUserPermissionsReturnsOnCall = make(map[int]struct {
			result1 *permission.ListUserPermissionsOutput
		})
	}
	fake.listUserPermissionsReturnsOnCall[i] = struct {
		result1 *permission.ListUserPermissionsOutput
	}{result1}
}

func (fake *ServiceFake) RemoveRolePermission(arg1 context.Context, arg2 *permission.RemoveRolePermissionInput) *permission.RemoveRolePermissionOutput {
	fake.removeRolePermissionMutex.Lock()
	ret, specificReturn := fake.removeRolePermissionReturnsOnCall[len(fake.removeRolePermissionArgsForCall)]
	fake.removeRolePermissionArgsForCall = append(fake.removeRolePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.RemoveRolePermissionInput
	}{arg1, arg2})
	stub := fake.RemoveRolePermissionStub
	fakeReturns := fake.removeRolePermissionReturns
	fake.recordInvocation("RemoveRolePermission", []interface{}{arg1, arg2})
	fake.removeRolePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RemoveRolePermissionCallCount() int {
	fake.removeRolePermissionMutex.RLock()
	defer fake.removeRolePermissionMutex.RUnlock()
	return len(fake.removeRolePermissionArgsForCall)
}

func (fake *ServiceFake) RemoveRolePermissionCalls(stub func(context.Context, *permission.RemoveRolePermissionInput) *permission.RemoveRolePermissionOutput) {
	fake.removeRolePermissionMutex.Lock()
	defer fake.removeRolePermissionMutex.Unlock()
	fake.RemoveRolePermissionStub = stub
}

func (fake *ServiceFake) RemoveRolePermissionArgsForCall(i int) (context.Context, *permission.RemoveRolePermissionInput) {
	fake.removeRolePermissionMutex.RLock()
	defer fake.removeRolePermissionMutex.RUnlock()
	argsForCall := fake.removeRolePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RemoveRolePermissionReturns(result1 *permission.RemoveRolePermissionOutput) {
	fake.removeRolePermissionMutex.Lock()
	defer fake.removeRolePermissionMutex.Unlock()
	fake.RemoveRolePermissionStub = nil
	fake.removeRolePermissionReturns = struct {
		result1 *permission.RemoveRolePermissionOutput
	}{result1}
}

func (fake *ServiceFake) RemoveRolePermissionReturnsOnCall(i int, result1 *permission.RemoveRolePermissionOutput) {
	fake.removeRolePermissionMutex.Lock()
	defer fake.removeRolePermissionMutex.Unlock()
	fake.RemoveRolePermissionStub = nil
	if fake.removeRolePermissionReturnsOnCall == nil {
		fake.removeRolePermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.RemoveRolePermissionOutput
		})
	}
	fake.removeRolePermissionReturnsOnCall[i] = struct {
		result1 *permission.RemoveRolePermissionOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermission(arg1 context.Context, arg2 *permission.RevokePermissionInput) *permission.RevokePermissionOutput {
	fake.revokePermissionMutex.Lock()
	ret, specificReturn := fake.revokePermissionReturnsOnCall[len(fake.revokePermissionArgsForCall)]
	fake.revokePermissionArgsForCall = append(fake.revokePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.RevokePermissionInput
	}{arg1, arg2})
	stub := fake.RevokePermissionStub
	fakeReturns := fake.revokePermissionReturns
	fake.recordInvocation("RevokePermission", []interface{}{arg1, arg2})
	fake.revokePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RevokePermissionCallCount() int {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	return len(fake.revokePermissionArgsForCall)
}

func (fake *ServiceFake) RevokePermissionCalls(stub func(context.Context, *permission.RevokePermissionInput) *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = stub
}

func (fake *ServiceFake) RevokePermissionArgsForCall(i int) (context.Context, *permission.RevokePermissionInput) {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	argsForCall := fake.revokePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RevokePermissionReturns(result1 *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	fake.revokePermissionReturns = struct {
		result1 *permission.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermissionReturnsOnCall(i int, result1 *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	if fake.revokePermissionReturnsOnCall == nil {
		fake.revokePermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.RevokePermissionOutput
		})
	}
	fake.revokePermissionReturnsOnCall[i] = struct {
		result1 *permission.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRole(arg1 context.Context, arg2 *permission.UnassignRoleInput) *permission.UnassignRoleOutput {
	fake.unassignRoleMutex.Lock()
	ret, specificReturn := fake.unassignRoleReturnsOnCall[len(fake.unassignRoleArgsForCall)]
	fake.unassignRoleArgsForCall = append(fake.unassignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.UnassignRoleInput
	}{arg1, arg2})
	stub := fake.UnassignRoleStub
	fakeReturns := fake.unassignRoleReturns
	fake.recordInvocation("UnassignRole", []interface{}{arg1, arg2})
	fake.unassignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UnassignRoleCallCount() int {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	return len(fake.unassignRoleArgsForCall)
}

func (fake *ServiceFake) UnassignRoleCalls(stub func(context.Context, *permission.UnassignRoleInput) *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = stub
}

func (fake *ServiceFake) UnassignRoleArgsForCall(i int) (context.Context, *permission.UnassignRoleInput) {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	argsForCall := fake.unassignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UnassignRoleReturns(result1 *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	fake.unassignRoleReturns = struct {
		result1 *permission.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRoleReturnsOnCall(i int, result1 *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	if fake.unassignRoleReturnsOnCall == nil {
		fake.unassignRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.UnassignRoleOutput
		})
	}
	fake.unassignRoleReturnsOnCall[i] = struct {
		result1 *permission.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ permission.Service = new(ServiceFake)
