// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/permission"
)

type ServiceFake struct {
	AssignPermissionToRoleStub        func(context.Context, *permission.AssignPermissionToRoleInput) *permission.AssignPermissionToRoleOutput
	assignPermissionToRoleMutex       sync.RWMutex
	assignPermissionToRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.AssignPermissionToRoleInput
	}
	assignPermissionToRoleReturns struct {
		result1 *permission.AssignPermissionToRoleOutput
	}
	assignPermissionToRoleReturnsOnCall map[int]struct {
		result1 *permission.AssignPermissionToRoleOutput
	}
	AssignRoleStub        func(context.Context, *permission.AssignRoleInput) *permission.AssignRoleOutput
	assignRoleMutex       sync.RWMutex
	assignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.AssignRoleInput
	}
	assignRoleReturns struct {
		result1 *permission.AssignRoleOutput
	}
	assignRoleReturnsOnCall map[int]struct {
		result1 *permission.AssignRoleOutput
	}
	CheckPermissionStub        func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput
	checkPermissionMutex       sync.RWMutex
	checkPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}
	checkPermissionReturns struct {
		result1 *permission.CheckPermissionOutput
	}
	checkPermissionReturnsOnCall map[int]struct {
		result1 *permission.CheckPermissionOutput
	}
	RemovePermissionFromRoleStub        func(context.Context, *permission.RemovePermissionFromRoleInput) *permission.RemovePermissionFromRoleOutput
	removePermissionFromRoleMutex       sync.RWMutex
	removePermissionFromRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.RemovePermissionFromRoleInput
	}
	removePermissionFromRoleReturns struct {
		result1 *permission.RemovePermissionFromRoleOutput
	}
	removePermissionFromRoleReturnsOnCall map[int]struct {
		result1 *permission.RemovePermissionFromRoleOutput
	}
	UnassignRoleStub        func(context.Context, *permission.UnassignRoleInput) *permission.UnassignRoleOutput
	unassignRoleMutex       sync.RWMutex
	unassignRoleArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.UnassignRoleInput
	}
	unassignRoleReturns struct {
		result1 *permission.UnassignRoleOutput
	}
	unassignRoleReturnsOnCall map[int]struct {
		result1 *permission.UnassignRoleOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) AssignPermissionToRole(arg1 context.Context, arg2 *permission.AssignPermissionToRoleInput) *permission.AssignPermissionToRoleOutput {
	fake.assignPermissionToRoleMutex.Lock()
	ret, specificReturn := fake.assignPermissionToRoleReturnsOnCall[len(fake.assignPermissionToRoleArgsForCall)]
	fake.assignPermissionToRoleArgsForCall = append(fake.assignPermissionToRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.AssignPermissionToRoleInput
	}{arg1, arg2})
	stub := fake.AssignPermissionToRoleStub
	fakeReturns := fake.assignPermissionToRoleReturns
	fake.recordInvocation("AssignPermissionToRole", []interface{}{arg1, arg2})
	fake.assignPermissionToRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AssignPermissionToRoleCallCount() int {
	fake.assignPermissionToRoleMutex.RLock()
	defer fake.assignPermissionToRoleMutex.RUnlock()
	return len(fake.assignPermissionToRoleArgsForCall)
}

func (fake *ServiceFake) AssignPermissionToRoleCalls(stub func(context.Context, *permission.AssignPermissionToRoleInput) *permission.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = stub
}

func (fake *ServiceFake) AssignPermissionToRoleArgsForCall(i int) (context.Context, *permission.AssignPermissionToRoleInput) {
	fake.assignPermissionToRoleMutex.RLock()
	defer fake.assignPermissionToRoleMutex.RUnlock()
	argsForCall := fake.assignPermissionToRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AssignPermissionToRoleReturns(result1 *permission.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = nil
	fake.assignPermissionToRoleReturns = struct {
		result1 *permission.AssignPermissionToRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignPermissionToRoleReturnsOnCall(i int, result1 *permission.AssignPermissionToRoleOutput) {
	fake.assignPermissionToRoleMutex.Lock()
	defer fake.assignPermissionToRoleMutex.Unlock()
	fake.AssignPermissionToRoleStub = nil
	if fake.assignPermissionToRoleReturnsOnCall == nil {
		fake.assignPermissionToRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.AssignPermissionToRoleOutput
		})
	}
	fake.assignPermissionToRoleReturnsOnCall[i] = struct {
		result1 *permission.AssignPermissionToRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignRole(arg1 context.Context, arg2 *permission.AssignRoleInput) *permission.AssignRoleOutput {
	fake.assignRoleMutex.Lock()
	ret, specificReturn := fake.assignRoleReturnsOnCall[len(fake.assignRoleArgsForCall)]
	fake.assignRoleArgsForCall = append(fake.assignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.AssignRoleInput
	}{arg1, arg2})
	stub := fake.AssignRoleStub
	fakeReturns := fake.assignRoleReturns
	fake.recordInvocation("AssignRole", []interface{}{arg1, arg2})
	fake.assignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) AssignRoleCallCount() int {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	return len(fake.assignRoleArgsForCall)
}

func (fake *ServiceFake) AssignRoleCalls(stub func(context.Context, *permission.AssignRoleInput) *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = stub
}

func (fake *ServiceFake) AssignRoleArgsForCall(i int) (context.Context, *permission.AssignRoleInput) {
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	argsForCall := fake.assignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) AssignRoleReturns(result1 *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	fake.assignRoleReturns = struct {
		result1 *permission.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) AssignRoleReturnsOnCall(i int, result1 *permission.AssignRoleOutput) {
	fake.assignRoleMutex.Lock()
	defer fake.assignRoleMutex.Unlock()
	fake.AssignRoleStub = nil
	if fake.assignRoleReturnsOnCall == nil {
		fake.assignRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.AssignRoleOutput
		})
	}
	fake.assignRoleReturnsOnCall[i] = struct {
		result1 *permission.AssignRoleOutput
	}{result1}
}

func (fake *ServiceFake) CheckPermission(arg1 context.Context, arg2 *permission.CheckPermissionInput) *permission.CheckPermissionOutput {
	fake.checkPermissionMutex.Lock()
	ret, specificReturn := fake.checkPermissionReturnsOnCall[len(fake.checkPermissionArgsForCall)]
	fake.checkPermissionArgsForCall = append(fake.checkPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}{arg1, arg2})
	stub := fake.CheckPermissionStub
	fakeReturns := fake.checkPermissionReturns
	fake.recordInvocation("CheckPermission", []interface{}{arg1, arg2})
	fake.checkPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) CheckPermissionCallCount() int {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	return len(fake.checkPermissionArgsForCall)
}

func (fake *ServiceFake) CheckPermissionCalls(stub func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = stub
}

func (fake *ServiceFake) CheckPermissionArgsForCall(i int) (context.Context, *permission.CheckPermissionInput) {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	argsForCall := fake.checkPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) CheckPermissionReturns(result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	fake.checkPermissionReturns = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) CheckPermissionReturnsOnCall(i int, result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	if fake.checkPermissionReturnsOnCall == nil {
		fake.checkPermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.CheckPermissionOutput
		})
	}
	fake.checkPermissionReturnsOnCall[i] = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) RemovePermissionFromRole(arg1 context.Context, arg2 *permission.RemovePermissionFromRoleInput) *permission.RemovePermissionFromRoleOutput {
	fake.removePermissionFromRoleMutex.Lock()
	ret, specificReturn := fake.removePermissionFromRoleReturnsOnCall[len(fake.removePermissionFromRoleArgsForCall)]
	fake.removePermissionFromRoleArgsForCall = append(fake.removePermissionFromRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.RemovePermissionFromRoleInput
	}{arg1, arg2})
	stub := fake.RemovePermissionFromRoleStub
	fakeReturns := fake.removePermissionFromRoleReturns
	fake.recordInvocation("RemovePermissionFromRole", []interface{}{arg1, arg2})
	fake.removePermissionFromRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RemovePermissionFromRoleCallCount() int {
	fake.removePermissionFromRoleMutex.RLock()
	defer fake.removePermissionFromRoleMutex.RUnlock()
	return len(fake.removePermissionFromRoleArgsForCall)
}

func (fake *ServiceFake) RemovePermissionFromRoleCalls(stub func(context.Context, *permission.RemovePermissionFromRoleInput) *permission.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = stub
}

func (fake *ServiceFake) RemovePermissionFromRoleArgsForCall(i int) (context.Context, *permission.RemovePermissionFromRoleInput) {
	fake.removePermissionFromRoleMutex.RLock()
	defer fake.removePermissionFromRoleMutex.RUnlock()
	argsForCall := fake.removePermissionFromRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RemovePermissionFromRoleReturns(result1 *permission.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = nil
	fake.removePermissionFromRoleReturns = struct {
		result1 *permission.RemovePermissionFromRoleOutput
	}{result1}
}

func (fake *ServiceFake) RemovePermissionFromRoleReturnsOnCall(i int, result1 *permission.RemovePermissionFromRoleOutput) {
	fake.removePermissionFromRoleMutex.Lock()
	defer fake.removePermissionFromRoleMutex.Unlock()
	fake.RemovePermissionFromRoleStub = nil
	if fake.removePermissionFromRoleReturnsOnCall == nil {
		fake.removePermissionFromRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.RemovePermissionFromRoleOutput
		})
	}
	fake.removePermissionFromRoleReturnsOnCall[i] = struct {
		result1 *permission.RemovePermissionFromRoleOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRole(arg1 context.Context, arg2 *permission.UnassignRoleInput) *permission.UnassignRoleOutput {
	fake.unassignRoleMutex.Lock()
	ret, specificReturn := fake.unassignRoleReturnsOnCall[len(fake.unassignRoleArgsForCall)]
	fake.unassignRoleArgsForCall = append(fake.unassignRoleArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.UnassignRoleInput
	}{arg1, arg2})
	stub := fake.UnassignRoleStub
	fakeReturns := fake.unassignRoleReturns
	fake.recordInvocation("UnassignRole", []interface{}{arg1, arg2})
	fake.unassignRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) UnassignRoleCallCount() int {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	return len(fake.unassignRoleArgsForCall)
}

func (fake *ServiceFake) UnassignRoleCalls(stub func(context.Context, *permission.UnassignRoleInput) *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = stub
}

func (fake *ServiceFake) UnassignRoleArgsForCall(i int) (context.Context, *permission.UnassignRoleInput) {
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	argsForCall := fake.unassignRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) UnassignRoleReturns(result1 *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	fake.unassignRoleReturns = struct {
		result1 *permission.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) UnassignRoleReturnsOnCall(i int, result1 *permission.UnassignRoleOutput) {
	fake.unassignRoleMutex.Lock()
	defer fake.unassignRoleMutex.Unlock()
	fake.UnassignRoleStub = nil
	if fake.unassignRoleReturnsOnCall == nil {
		fake.unassignRoleReturnsOnCall = make(map[int]struct {
			result1 *permission.UnassignRoleOutput
		})
	}
	fake.unassignRoleReturnsOnCall[i] = struct {
		result1 *permission.UnassignRoleOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.assignPermissionToRoleMutex.RLock()
	defer fake.assignPermissionToRoleMutex.RUnlock()
	fake.assignRoleMutex.RLock()
	defer fake.assignRoleMutex.RUnlock()
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	fake.removePermissionFromRoleMutex.RLock()
	defer fake.removePermissionFromRoleMutex.RUnlock()
	fake.unassignRoleMutex.RLock()
	defer fake.unassignRoleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ permission.Service = new(ServiceFake)
