// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/ariesmaulana/ars-kit/src/app/permission"
)

type ServiceFake struct {
	CheckPermissionStub        func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput
	checkPermissionMutex       sync.RWMutex
	checkPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}
	checkPermissionReturns struct {
		result1 *permission.CheckPermissionOutput
	}
	checkPermissionReturnsOnCall map[int]struct {
		result1 *permission.CheckPermissionOutput
	}
	GrantPermissionStub        func(context.Context, *permission.GrantPermissionInput) *permission.GrantPermissionOutput
	grantPermissionMutex       sync.RWMutex
	grantPermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.GrantPermissionInput
	}
	grantPermissionReturns struct {
		result1 *permission.GrantPermissionOutput
	}
	grantPermissionReturnsOnCall map[int]struct {
		result1 *permission.GrantPermissionOutput
	}
	RevokePermissionStub        func(context.Context, *permission.RevokePermissionInput) *permission.RevokePermissionOutput
	revokePermissionMutex       sync.RWMutex
	revokePermissionArgsForCall []struct {
		arg1 context.Context
		arg2 *permission.RevokePermissionInput
	}
	revokePermissionReturns struct {
		result1 *permission.RevokePermissionOutput
	}
	revokePermissionReturnsOnCall map[int]struct {
		result1 *permission.RevokePermissionOutput
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceFake) CheckPermission(arg1 context.Context, arg2 *permission.CheckPermissionInput) *permission.CheckPermissionOutput {
	fake.checkPermissionMutex.Lock()
	ret, specificReturn := fake.checkPermissionReturnsOnCall[len(fake.checkPermissionArgsForCall)]
	fake.checkPermissionArgsForCall = append(fake.checkPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.CheckPermissionInput
	}{arg1, arg2})
	stub := fake.CheckPermissionStub
	fakeReturns := fake.checkPermissionReturns
	fake.recordInvocation("CheckPermission", []interface{}{arg1, arg2})
	fake.checkPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) CheckPermissionCallCount() int {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	return len(fake.checkPermissionArgsForCall)
}

func (fake *ServiceFake) CheckPermissionCalls(stub func(context.Context, *permission.CheckPermissionInput) *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = stub
}

func (fake *ServiceFake) CheckPermissionArgsForCall(i int) (context.Context, *permission.CheckPermissionInput) {
	fake.checkPermissionMutex.RLock()
	defer fake.checkPermissionMutex.RUnlock()
	argsForCall := fake.checkPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) CheckPermissionReturns(result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	fake.checkPermissionReturns = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) CheckPermissionReturnsOnCall(i int, result1 *permission.CheckPermissionOutput) {
	fake.checkPermissionMutex.Lock()
	defer fake.checkPermissionMutex.Unlock()
	fake.CheckPermissionStub = nil
	if fake.checkPermissionReturnsOnCall == nil {
		fake.checkPermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.CheckPermissionOutput
		})
	}
	fake.checkPermissionReturnsOnCall[i] = struct {
		result1 *permission.CheckPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermission(arg1 context.Context, arg2 *permission.GrantPermissionInput) *permission.GrantPermissionOutput {
	fake.grantPermissionMutex.Lock()
	ret, specificReturn := fake.grantPermissionReturnsOnCall[len(fake.grantPermissionArgsForCall)]
	fake.grantPermissionArgsForCall = append(fake.grantPermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.GrantPermissionInput
	}{arg1, arg2})
	stub := fake.GrantPermissionStub
	fakeReturns := fake.grantPermissionReturns
	fake.recordInvocation("GrantPermission", []interface{}{arg1, arg2})
	fake.grantPermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) GrantPermissionCallCount() int {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	return len(fake.grantPermissionArgsForCall)
}

func (fake *ServiceFake) GrantPermissionCalls(stub func(context.Context, *permission.GrantPermissionInput) *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = stub
}

func (fake *ServiceFake) GrantPermissionArgsForCall(i int) (context.Context, *permission.GrantPermissionInput) {
	fake.grantPermissionMutex.RLock()
	defer fake.grantPermissionMutex.RUnlock()
	argsForCall := fake.grantPermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) GrantPermissionReturns(result1 *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	fake.grantPermissionReturns = struct {
		result1 *permission.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) GrantPermissionReturnsOnCall(i int, result1 *permission.GrantPermissionOutput) {
	fake.grantPermissionMutex.Lock()
	defer fake.grantPermissionMutex.Unlock()
	fake.GrantPermissionStub = nil
	if fake.grantPermissionReturnsOnCall == nil {
		fake.grantPermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.GrantPermissionOutput
		})
	}
	fake.grantPermissionReturnsOnCall[i] = struct {
		result1 *permission.GrantPermissionOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermission(arg1 context.Context, arg2 *permission.RevokePermissionInput) *permission.RevokePermissionOutput {
	fake.revokePermissionMutex.Lock()
	ret, specificReturn := fake.revokePermissionReturnsOnCall[len(fake.revokePermissionArgsForCall)]
	fake.revokePermissionArgsForCall = append(fake.revokePermissionArgsForCall, struct {
		arg1 context.Context
		arg2 *permission.RevokePermissionInput
	}{arg1, arg2})
	stub := fake.RevokePermissionStub
	fakeReturns := fake.revokePermissionReturns
	fake.recordInvocation("RevokePermission", []interface{}{arg1, arg2})
	fake.revokePermissionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ServiceFake) RevokePermissionCallCount() int {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	return len(fake.revokePermissionArgsForCall)
}

func (fake *ServiceFake) RevokePermissionCalls(stub func(context.Context, *permission.RevokePermissionInput) *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = stub
}

func (fake *ServiceFake) RevokePermissionArgsForCall(i int) (context.Context, *permission.RevokePermissionInput) {
	fake.revokePermissionMutex.RLock()
	defer fake.revokePermissionMutex.RUnlock()
	argsForCall := fake.revokePermissionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceFake) RevokePermissionReturns(result1 *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	fake.revokePermissionReturns = struct {
		result1 *permission.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) RevokePermissionReturnsOnCall(i int, result1 *permission.RevokePermissionOutput) {
	fake.revokePermissionMutex.Lock()
	defer fake.revokePermissionMutex.Unlock()
	fake.RevokePermissionStub = nil
	if fake.revokePermissionReturnsOnCall == nil {
		fake.revokePermissionReturnsOnCall = make(map[int]struct {
			result1 *permission.RevokePermissionOutput
		})
	}
	fake.revokePermissionReturnsOnCall[i] = struct {
		result1 *permission.RevokePermissionOutput
	}{result1}
}

func (fake *ServiceFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ permission.Service = new(ServiceFake)
