// Code generated by counterfeiter. DO NOT EDIT.
package uploadfakes

import (
	"context"
	"sync"
	"time"

	"github.com/ariesmaulana/ars-kit/src/app/upload"
)

type UploaderFake struct {
	DeleteStub        func(context.Context, string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	PresignedURLStub        func(context.Context, string, time.Duration) (string, error)
	presignedURLMutex       sync.RWMutex
	presignedURLArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
	}
	presignedURLReturns struct {
		result1 string
		result2 error
	}
	presignedURLReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	UploadStub        func(context.Context, upload.UploadRequest) (*upload.UploadResult, error)
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		arg1 context.Context
		arg2 upload.UploadRequest
	}
	uploadReturns struct {
		result1 *upload.UploadResult
		result2 error
	}
	uploadReturnsOnCall map[int]struct {
		result1 *upload.UploadResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *UploaderFake) Delete(arg1 context.Context, arg2 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *UploaderFake) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *UploaderFake) DeleteCalls(stub func(context.Context, string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *UploaderFake) DeleteArgsForCall(i int) (context.Context, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *UploaderFake) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *UploaderFake) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *UploaderFake) PresignedURL(arg1 context.Context, arg2 string, arg3 time.Duration) (string, error) {
	fake.presignedURLMutex.Lock()
	ret, specificReturn := fake.presignedURLReturnsOnCall[len(fake.presignedURLArgsForCall)]
	fake.presignedURLArgsForCall = append(fake.presignedURLArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
	}{arg1, arg2, arg3})
	stub := fake.PresignedURLStub
	fakeReturns := fake.presignedURLReturns
	fake.recordInvocation("PresignedURL", []interface{}{arg1, arg2, arg3})
	fake.presignedURLMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *UploaderFake) PresignedURLCallCount() int {
	fake.presignedURLMutex.RLock()
	defer fake.presignedURLMutex.RUnlock()
	return len(fake.presignedURLArgsForCall)
}

func (fake *UploaderFake) PresignedURLCalls(stub func(context.Context, string, time.Duration) (string, error)) {
	fake.presignedURLMutex.Lock()
	defer fake.presignedURLMutex.Unlock()
	fake.PresignedURLStub = stub
}

func (fake *UploaderFake) PresignedURLArgsForCall(i int) (context.Context, string, time.Duration) {
	fake.presignedURLMutex.RLock()
	defer fake.presignedURLMutex.RUnlock()
	argsForCall := fake.presignedURLArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *UploaderFake) PresignedURLReturns(result1 string, result2 error) {
	fake.presignedURLMutex.Lock()
	defer fake.presignedURLMutex.Unlock()
	fake.PresignedURLStub = nil
	fake.presignedURLReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *UploaderFake) PresignedURLReturnsOnCall(i int, result1 string, result2 error) {
	fake.presignedURLMutex.Lock()
	defer fake.presignedURLMutex.Unlock()
	fake.PresignedURLStub = nil
	if fake.presignedURLReturnsOnCall == nil {
		fake.presignedURLReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.presignedURLReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *UploaderFake) Upload(arg1 context.Context, arg2 upload.UploadRequest) (*upload.UploadResult, error) {
	fake.uploadMutex.Lock()
	ret, specificReturn := fake.uploadReturnsOnCall[len(fake.uploadArgsForCall)]
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		arg1 context.Context
		arg2 upload.UploadRequest
	}{arg1, arg2})
	stub := fake.UploadStub
	fakeReturns := fake.uploadReturns
	fake.recordInvocation("Upload", []interface{}{arg1, arg2})
	fake.uploadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *UploaderFake) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *UploaderFake) UploadCalls(stub func(context.Context, upload.UploadRequest) (*upload.UploadResult, error)) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = stub
}

func (fake *UploaderFake) UploadArgsForCall(i int) (context.Context, upload.UploadRequest) {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	argsForCall := fake.uploadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *UploaderFake) UploadReturns(result1 *upload.UploadResult, result2 error) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 *upload.UploadResult
		result2 error
	}{result1, result2}
}

func (fake *UploaderFake) UploadReturnsOnCall(i int, result1 *upload.UploadResult, result2 error) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = nil
	if fake.uploadReturnsOnCall == nil {
		fake.uploadReturnsOnCall = make(map[int]struct {
			result1 *upload.UploadResult
			result2 error
		})
	}
	fake.uploadReturnsOnCall[i] = struct {
		result1 *upload.UploadResult
		result2 error
	}{result1, result2}
}

func (fake *UploaderFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *UploaderFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ upload.Uploader = new(UploaderFake)
